# Đề tài 4 — Notebook 02: Huấn luyện, đánh giá và quét ngưỡng

**Điều kiện tiên quyết:** đã chạy xong `01_data_prep.ipynb` (phải tồn tại `data/yolo/` và `configs/helmet.yaml`).

---
| Mục | Yêu cầu tương ứng |
|---|---|
| §2 | *Fine-tune YOLOv8n từ trọng số COCO* — **bắt buộc** |
| §3 | *Báo cáo mAP@0.5, mAP@0.5:0.95, precision–recall curve cho từng lớp* — **bắt buộc** |
| §4 | *Ảnh hưởng của ngưỡng confidence (quét ≥ 5 giá trị)* — **bắt buộc** |
| §5 | *Ảnh hưởng của ngưỡng NMS (quét ≥ 5 giá trị)* — **bắt buộc** |
| §6 | *Giải thích anchor box / IoU / NMS bằng lời **và bằng ví dụ minh họa từ chính mô hình của nhóm*** — **bắt buộc** |
| §7 | *Đo ảnh hưởng của độ phân giải đầu vào (416 / 640 / 960) tới mAP và FPS* — **nâng cao** |
| §8 | Đo FPS chuẩn, ghi nhật ký thí nghiệm |

**Nguyên tắc giữ cho thí nghiệm công bằng:** mọi cấu hình dùng **cùng seed = 42**, **cùng số epoch**, **cùng phép chia dữ liệu**, và **cùng một tập val** để chọn ngưỡng. Tập `test` chỉ đụng vào đúng một lần ở §3.

## 0. Thiết lập

In [1]:
import sys, os, time, json, math, warnings
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from PIL import Image

import config
from config import (YOLO_DIR, ARTIFACT_DIR, RUNS_DIR, DATA_YAML, CLASS_NAMES,
                    SEED, set_seed, describe_environment)
import exp_log
from exp_log import log_run, read_log, metrics_from_ultralytics, per_class_table

from ultralytics import YOLO
from ultralytics.utils import LOGGER
warnings.filterwarnings("ignore", category=UserWarning)

set_seed(SEED)
plt.rcParams.update({"figure.dpi": 110, "font.size": 10, "axes.grid": True,
                     "grid.alpha": 0.3, "figure.autolayout": True})
pd.set_option("display.width", 150)

env = describe_environment()
print(json.dumps(env, indent=2, ensure_ascii=False))
assert DATA_YAML.exists(), "Chưa có configs/helmet.yaml — hãy chạy notebook 01 trước."
HAS_GPU = torch.cuda.is_available()
DEVICE = 0 if HAS_GPU else "cpu"
if not HAS_GPU:
    print()
    print("[CẢNH BÁO] Không thấy GPU — notebook vẫn chạy được nhưng rất chậm.")
    print("Để chấm nhanh: đặt FORCE_RETRAIN = False ở §2 để dùng lại checkpoint kèm theo.")

{
  "python": "3.10.20",
  "platform": "Linux-7.0.0-28-generic-x86_64-with-glibc2.39",
  "seed": 42,
  "torch": "2.7.1+cu126",
  "cuda_available": true,
  "gpu": "NVIDIA GeForce RTX 4090",
  "cuda": "12.6",
  "vram_gb": 23.5,
  "ultralytics": "8.3.40"
}


Nạp thư viện, thêm `src/` vào path, cố định seed, rồi kiểm tra GPU. Nếu không có GPU, code **không dừng chương trình** (không còn `assert` cứng như bản trước) mà chỉ in cảnh báo và tự chuyển `DEVICE = "cpu"`.

**Output nói gì.** Môi trường chạy: **RTX 4090, torch 2.7.1+cu126, ultralytics 8.3.40**. `cuda_available: true` nên `HAS_GPU = True`, không có cảnh báo nào được in ra. Đây là bằng chứng môi trường cần chụp lại cho phụ lục báo cáo — mọi con số phía sau đều sinh ra trên cấu hình này.

In [2]:
# ================= SIÊU THAM SỐ DÙNG CHUNG CHO MỌI LƯỢT TRAIN =================
# Nguyên tắc: KHÔNG dùng giá trị "auto" hay để mặc định ngầm. Mọi thứ ảnh hưởng
# tới kết quả đều phải hiện ra ở đây để (a) thí nghiệm công bằng giữa các cấu
# hình, (b) nhóm giải thích được từng dòng khi bảo vệ.

OPTIM = dict(
    # --- Thuật toán tối ưu (Bài 4, tr.10-12) ---
    # Ultralytics mặc định optimizer="auto" -> tự chọn AdamW + lr riêng và KHÔNG
    # in ra. Ta khai báo tường minh SGD + momentum: đúng thuật toán đã học, và
    # theo Bài 4 tr.31 thì SGD+momentum có thể vượt Adam nếu chịu khó chỉnh lr.
    optimizer="SGD",
    lr0=0.01,             # learning rate ban đầu
    lrf=0.01,             # lr cuối = lr0 * lrf
    momentum=0.937,       # hệ số "ma sát" rho (Bài 4 tr.10)
    weight_decay=5e-4,    # chính quy hóa L2 (Bài 4 tr.42)
    warmup_epochs=3.0,    # linear warmup (Bài 4 tr.38)
    cos_lr=True,          # cosine annealing (Bài 4 tr.35)
)

AUGMENT = dict(
    # --- Tăng cường dữ liệu (Bài 4, tr.52-57) ---
    # Ultralytics BẬT SẴN một loạt phép tăng cường kể cả khi ta không viết gì.
    # Khai báo lại đầy đủ ở đây, kể cả các phép bị TẮT, để không có phép biến
    # đổi nào tác động lên dữ liệu mà nhóm không biết.
    fliplr=0.5,           # lật ngang            (Bài 4 tr.53)
    scale=0.5,            # phóng/thu ngẫu nhiên (Bài 4 tr.54)
    translate=0.1,        # tịnh tiến            (Bài 4 tr.56)
    hsv_h=0.015,          # }
    hsv_s=0.7,            # } color jitter       (Bài 4 tr.55)
    hsv_v=0.4,            # }
    mosaic=1.0,           # ghép 4 ảnh train thành 1 ảnh -> mỗi batch thấy nhiều
                          # ngữ cảnh và nhiều vật thể nhỏ hơn. KHÔNG có trong
                          # bài giảng (đến từ YOLOv4) nhưng là mặc định của
                          # ultralytics; giữ lại vì có lợi rõ rệt cho vật thể nhỏ
                          # — vốn chiếm đa số trong bộ dữ liệu này (xem NB01 §6).
    close_mosaic=10,      # tắt mosaic ở 10 epoch cuối để mô hình "hạ cánh" trên
                          # ảnh thật, tránh lệch phân bố giữa train và test.
    # --- Các phép TẮT tường minh, kèm lý do ---
    flipud=0.0,           # lật dọc: vô nghĩa, mũ bảo hiểm luôn nằm trên đầu
    degrees=0.0,          # xoay: cùng lý do
    shear=0.0,            # trượt nghiêng (Bài 4 tr.56) - không hợp bài toán
    perspective=0.0,      # biến đổi phối cảnh
    mixup=0.0,            # Mixup (Bài 4 tr.57): có học, nhưng với bài toán phát
                          # hiện thì việc trộn ảnh làm nhãn hộp bị chồng chập,
                          # khó diễn giải -> tắt.
    copy_paste=0.0,       # cần nhãn mask, dữ liệu của ta chỉ có hộp
)

COMMON = dict(
    data=str(DATA_YAML),
    epochs=80,            # đề bài gợi ý ~50 epoch/lượt; 80 để có biên an toàn
                          # mà vẫn nằm trong ngân sách GPU miễn phí.
    batch=32,             # vừa VRAM của T4/P100 (Colab, Kaggle) ở 640px
    imgsz=None,           # đặt riêng ở từng lượt train
    seed=SEED,
    deterministic=True,
    workers=8,
    device=DEVICE,
    project=str(RUNS_DIR),
    patience=25,          # early stopping (Bài 4 tr.40)
    cache=False,          # đặt "ram" nếu máy >16GB RAM để train nhanh hơn;
                          # mặc định False cho an toàn trên Colab.
    val=True,
    plots=True,
    exist_ok=True,
    verbose=False,
    **OPTIM,
    **AUGMENT,
)
COMMON.pop("imgsz")       # imgsz luôn được truyền riêng, tránh trùng tham số
BASE_IMGSZ = 640

print("Tối ưu   :", json.dumps(OPTIM, ensure_ascii=False))
print("Tăng cường:", json.dumps(AUGMENT, ensure_ascii=False))
print(f"epochs={COMMON['epochs']}  batch={COMMON['batch']}  imgsz={BASE_IMGSZ}  seed={SEED}")

Tối ưu   : {"optimizer": "SGD", "lr0": 0.01, "lrf": 0.01, "momentum": 0.937, "weight_decay": 0.0005, "warmup_epochs": 3.0, "cos_lr": true}
Tăng cường: {"fliplr": 0.5, "scale": 0.5, "translate": 0.1, "hsv_h": 0.015, "hsv_s": 0.7, "hsv_v": 0.4, "mosaic": 1.0, "close_mosaic": 10, "flipud": 0.0, "degrees": 0.0, "shear": 0.0, "perspective": 0.0, "mixup": 0.0, "copy_paste": 0.0}
epochs=80  batch=32  imgsz=640  seed=42


Ba dòng in ra chính là cấu hình **thật sự được dùng để train**:

```
optimizer=SGD, lr0=0.01, momentum=0.937, weight_decay=0.0005, cos_lr=True
mosaic=1.0, fliplr=0.5, scale=0.5, translate=0.1, hsv jitter, flipud/degrees/shear/mixup=0
epochs=80  batch=32  imgsz=640  seed=42
```

Khi đọc log huấn luyện ở cell tiếp theo, đối chiếu ngược lại đúng các con số này trong dòng `engine/trainer: ...` để xác nhận ultralytics đã nhận đúng cấu hình, không bị giá trị mặc định nào đè lên.

## 1–2. Fine-tune YOLOv8n từ trọng số COCO

Trọng số COCO đã học sẵn các đặc trưng thị giác tổng quát (cạnh, kết cấu, hình dáng người) từ 118k ảnh / 80 lớp. Với 3.500 ảnh train, học lại những đặc trưng đó từ số 0 gần như chắc chắn thua. Ta chỉ cần điều chỉnh phần đầu ra và tinh chỉnh nhẹ backbone.
 lớp `Detect` cuối cùng của COCO có 80 kênh lớp, ta thay bằng 3 kênh. Ultralytics tự động làm việc này khi `data.yaml` khai `nc: 3`, và các trọng số còn lại được nạp lại từ checkpoint.

In [3]:
FORCE_RETRAIN = True          # đặt False để tái sử dụng checkpoint đã có
EP = COMMON["epochs"]
RUN_BASE = f"yolov8n_{BASE_IMGSZ}_e{EP}"   # tên suy ra từ cấu hình, không hardcode
best_ckpt = RUNS_DIR / RUN_BASE / "weights" / "best.pt"

if FORCE_RETRAIN or not best_ckpt.exists():
    set_seed(SEED)
    model = YOLO("yolov8n.pt")           # trọng số tiền huấn luyện trên COCO
    t0 = time.time()
    model.train(name=RUN_BASE, imgsz=BASE_IMGSZ, **COMMON)
    train_min = (time.time() - t0) / 60
    print(f"\nThời gian huấn luyện: {train_min:.1f} phút")
else:
    train_min = None
    print("Bỏ qua train, dùng checkpoint có sẵn:", best_ckpt)

assert best_ckpt.exists(), "Không tìm thấy best.pt — kiểm tra log train."
model = YOLO(str(best_ckpt))
print("Đã nạp:", best_ckpt)
print("Số tham số:", sum(p.numel() for p in model.model.parameters()))

New https://pypi.org/project/ultralytics/8.4.126 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/home/lablee/Documents/wm/projectdl/configs/helmet.yaml, epochs=80, time=None, patience=25, batch=32, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=8, project=/home/lablee/Documents/wm/projectdl/runs, name=yolov8n_640_e80, exist_ok=True, pretrained=True, optimizer=SGD, verbose=False, seed=42, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agno

train: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/train... 3501 images, 0 backgro


train: New cache created: /home/lablee/Documents/wm/projectdl/data/yolo/labels/train.cache


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val... 750 images, 0 backgrounds,


val: New cache created: /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache
Plotting labels to /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80/labels.jpg... 
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80
Starting training for 80 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/80      4.65G      1.542      2.223      1.358        108        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.884      0.432      0.513      0.284



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/80      4.91G      1.434      1.214      1.241         88        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.909      0.507      0.569       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/80      5.16G      1.434      1.148       1.23         74        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.887      0.491      0.543      0.306

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/80      4.71G      1.444      1.129      1.229         95        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.867       0.47      0.513      0.291

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/80      4.42G      1.426      1.063      1.228        139        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.899      0.467      0.531      0.314

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/80      4.87G      1.396       1.01      1.212        132        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.894      0.503      0.558      0.335



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/80      5.17G      1.371     0.9577      1.198         92        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.908      0.505      0.566      0.329



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/80      5.39G      1.374     0.9281      1.197         71        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.921      0.509      0.573      0.353

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/80      5.03G      1.354     0.9249       1.19         49        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.913      0.514      0.577      0.354



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/80      4.47G      1.368     0.9091      1.188         63        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.926      0.527      0.593      0.355



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/80      5.09G       1.33     0.8658      1.183         65        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.925      0.534      0.586      0.365



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/80      4.92G       1.33     0.8603       1.18        124        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.926      0.524      0.589      0.363



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/80       4.8G       1.32     0.8449      1.176         75        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.928      0.547      0.602      0.371



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/80      4.77G      1.321     0.8407      1.167         84        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.919      0.533      0.594      0.363



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/80      4.94G      1.311     0.8193      1.169         72        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.935       0.52      0.586      0.356



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/80      4.52G      1.304     0.8226      1.169         95        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.933      0.548        0.6      0.371



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/80      4.81G      1.297     0.8119      1.166         84        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.932      0.549      0.607      0.374



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/80      4.44G      1.299     0.7919      1.161         63        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.922      0.559      0.601      0.372



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/80      4.73G      1.294     0.7934      1.155         68        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.942      0.554      0.614      0.382



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/80      4.85G       1.29     0.7948      1.152        129        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.926      0.555      0.604      0.382



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/80      4.89G      1.267     0.7667      1.133        117        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.942      0.548      0.611      0.383



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/80      4.75G      1.272     0.7733      1.145        101        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.94      0.545      0.603      0.381



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/80      4.62G      1.268     0.7653      1.141        105        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.932      0.533      0.605      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/80      4.59G      1.252     0.7555      1.129        105        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.939      0.549       0.61      0.392



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/80      4.69G      1.254     0.7478      1.136         75        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.934      0.553      0.607      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/80      5.02G      1.268     0.7458      1.129        113        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.939      0.557      0.617      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/80      4.71G      1.241     0.7325       1.13         90        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.938      0.556      0.609      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/80      4.91G      1.237     0.7256      1.118         69        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.606       0.56      0.615       0.39



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/80      4.51G      1.249     0.7262      1.122        126        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.943      0.566      0.618      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/80      4.88G      1.232     0.7187      1.114         90        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.934      0.575      0.622      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/80      4.84G      1.243     0.7214      1.122         81        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.609      0.578      0.613      0.392



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/80      4.44G      1.209     0.7015      1.106         72        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.946      0.564      0.615      0.394

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      33/80      4.73G      1.231     0.7062      1.115        115        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.938       0.57      0.619      0.396



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      34/80      4.55G      1.213     0.6953        1.1        122        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.932      0.575      0.615      0.395



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      35/80      4.45G       1.21     0.6912      1.103         86        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.941      0.576      0.621      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      36/80      4.78G       1.21     0.6854      1.102         91        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867       0.61      0.566      0.614       0.39

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      37/80      4.77G      1.203     0.6888      1.103         62        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.606      0.571      0.616      0.397

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      38/80      4.89G      1.204     0.6743      1.101        104        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.946      0.558      0.616      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      39/80      4.92G      1.193     0.6746      1.098        130        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.948      0.574      0.623      0.398



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      40/80      4.49G      1.194      0.673      1.092         72        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.617      0.569      0.623      0.403

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      41/80      4.74G      1.204     0.6663      1.097         96        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.607      0.574      0.618      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      42/80      4.85G      1.178     0.6602      1.093        110        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.619      0.601      0.619      0.398



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      43/80      4.78G      1.172     0.6452      1.087         99        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.613      0.589       0.62        0.4

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      44/80      4.77G      1.165     0.6426       1.08         88        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.634      0.579      0.622      0.401

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      45/80       4.7G      1.171     0.6375      1.086         76        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.612      0.601      0.622      0.401

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      46/80      4.74G      1.164     0.6341      1.082         89        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.613      0.588      0.623      0.407



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      47/80      4.77G      1.161      0.631      1.076        108        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.633      0.574      0.623      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      48/80       5.1G      1.154     0.6275      1.075         72        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.615      0.565      0.622      0.405



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      49/80      4.78G      1.157     0.6154      1.074        104        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.619      0.595      0.622      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      50/80      4.76G      1.145     0.6161      1.072        102        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.617      0.599      0.624      0.404



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      51/80      4.91G       1.14     0.6074      1.065         64        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.62      0.573      0.623      0.405



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      52/80      5.05G      1.129      0.602      1.066         94        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.616      0.575      0.623      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      53/80      4.86G      1.137     0.6061      1.066         71        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.62      0.581      0.624      0.404



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      54/80      4.97G      1.134     0.5997       1.06         62        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.614      0.577      0.623      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      55/80      4.44G      1.124     0.5937      1.062         76        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.617      0.574      0.623      0.405



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      56/80      5.23G      1.129     0.5891      1.059         84        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.613      0.583      0.622      0.404



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      57/80      5.31G      1.118     0.5853      1.063         67        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.615      0.579      0.621      0.407



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      58/80      4.73G      1.114     0.5851      1.057         68        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.631      0.601      0.625       0.41



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      59/80      4.49G      1.104     0.5785      1.049         45        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.951      0.582      0.624      0.407



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      60/80      4.84G      1.108     0.5773      1.055        132        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.61      0.584      0.624      0.408



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      61/80      5.09G      1.103     0.5645      1.046         96        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.613      0.583      0.623      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      62/80      4.81G      1.095     0.5567      1.048        106        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867       0.62      0.576      0.622      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      63/80      5.05G      1.094     0.5644      1.047         75        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.616       0.58      0.623      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      64/80      5.17G      1.084     0.5609      1.041         54        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.595      0.605      0.626      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      65/80      4.52G      1.087     0.5518      1.039         95        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.615      0.582      0.625       0.41



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      66/80      4.41G      1.087     0.5579      1.043        108        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.619      0.582      0.624      0.409



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      67/80      4.55G      1.083     0.5565      1.043         82        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.623      0.579      0.624      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      68/80       4.6G      1.076     0.5441      1.037         87        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621      0.579      0.625       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      69/80      4.71G      1.073     0.5477      1.037         64        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621      0.582      0.627      0.412

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      70/80      4.41G       1.07     0.5398      1.039        123        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621       0.58      0.624       0.41
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      71/80         5G       1.06     0.4838      1.051         62        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.619       0.58      0.623      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      72/80      4.52G      1.059     0.4782      1.045         56        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.578      0.625      0.408



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      73/80      4.63G      1.045     0.4673      1.038         51        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.619       0.58      0.624      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      74/80      4.46G      1.051     0.4707      1.046         59        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867       0.62      0.581      0.625       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      75/80      4.11G      1.046     0.4634      1.043         69        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621       0.58      0.625       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      76/80      4.38G      1.041     0.4623       1.04        124        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.607      0.597      0.626       0.41



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      77/80      4.42G      1.042     0.4597       1.04         62        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.624      0.589      0.625      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      78/80      4.97G      1.042      0.461      1.041         44        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.614      0.592      0.625       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      79/80      4.61G      1.033     0.4554      1.033         54        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.616      0.593      0.625      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      80/80      4.43G      1.041     0.4613      1.043         69        640: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.629       0.59      0.625       0.41



80 epochs completed in 0.290 hours.
Optimizer stripped from /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80/weights/last.pt, 6.3MB
Optimizer stripped from /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80/weights/best.pt, 6.3MB

Validating /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80/weights/best.pt...
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
Model summary (fused): 168 layers, 3,006,233 parameters, 0 gradients, 8.1 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621      0.582      0.627      0.411
Speed: 0.1ms preprocess, 0.3ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80

Thời gian huấn luyện: 17.7 phút
Đã nạp: /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80/weights/best.pt
Số tham số: 3011433


Nạp `yolov8n.pt` (trọng số COCO), gọi `model.train(**COMMON)` — đây là bước fine-tune thật sự, tốn nhiều thời gian nhất trong cả notebook.

Log huấn luyện rất dài, nhưng có 5 điểm cần đọc:

1. **`Overriding model.yaml nc=80 with nc=3`** — dòng xác nhận quan trọng nhất. Ultralytics tự phát hiện `nc=3` từ `helmet.yaml` và thay tầng đầu ra 80 lớp (COCO) bằng 3 lớp. Đây chính là cơ chế "transfer learning" đã nói ở note markdown phía trên, được thực thi ngay tại dòng này.

2. Toàn bộ dòng `engine/trainer: ...` liệt kê **mọi tham số ultralytics thực nhận** — nên đối chiếu với khối `OPTIM`/`AUGMENT` ở cell trước: `optimizer=SGD, lr0=0.01, momentum=0.937, mosaic=1.0, patience=25...` khớp đúng những gì đã khai báo tường minh.

3. **`80 epochs completed in 0.290 hours`** (~17,4 phút thuần huấn luyện) — rất nhanh vì `batch=32` trên RTX 4090 24GB xử lý ảnh 416×416... khoan, imgsz=640 nhưng dữ liệu chỉ 5.000 ảnh nhỏ, nên một epoch chỉ mất khoảng 13 giây.

4. `Model summary (fused): 168 layers, 3.006.233 parameters` — đây là số tham số **sau khi gộp (fuse) Conv+BatchNorm** để tăng tốc suy luận. Dòng cuối cell in `Số tham số: 3.011.433` — nhiều hơn một chút vì đó là số tham số **trước khi fuse** (BatchNorm còn tách riêng). Chênh lệch ~5.200 tham số là bình thường, không phải lỗi.

5. **`Thời gian huấn luyện: 17.7 phút`** — số do chính code đo (`time.time()`), gồm cả bước validate cuối cùng, nên hơi nhỉnh hơn con số `0.290 giờ` ultralytics tự báo.

### Ảnh huấn luyện thực sự trông như thế nào?



In [4]:
# Mở ảnh batch huấn luyện do ultralytics lưu lại, để thấy tận mắt tác dụng
# của khối AUGMENT đã khai báo ở §0.
train_dir = RUNS_DIR / RUN_BASE
batch_imgs = sorted(train_dir.glob("train_batch*.jpg"))[:2]

if batch_imgs:
    fig, axes = plt.subplots(1, len(batch_imgs), figsize=(7.5 * len(batch_imgs), 7.5))
    axes = np.atleast_1d(axes)
    for ax, ip in zip(axes, batch_imgs):
        ax.imshow(Image.open(ip)); ax.axis("off"); ax.set_title(ip.name, fontsize=10)
    fig.suptitle("Ảnh đầu vào thật sau tăng cường dữ liệu (mosaic + jitter + lật + scale)",
                 fontsize=12)
    plt.savefig(ARTIFACT_DIR / "fig04b_augmented_batch.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("Đối chiếu với khối AUGMENT ở §0: mỗi khung là 4 ảnh train ghép lại,")
    print("khoảng một nửa số ô bị lật ngang, và màu giữa các ô lệch nhau.")
else:
    print("Chưa có train_batch*.jpg — chỉ xuất hiện sau khi đã chạy train ở cell trên.")

<Figure size 1650x825 with 2 Axes>

Đối chiếu với khối AUGMENT ở §0: mỗi khung là 4 ảnh train ghép lại,
khoảng một nửa số ô bị lật ngang, và màu giữa các ô lệch nhau.


Mỗi ảnh lớn là một lưới 4×4 = 16 ô, và **mỗi ô lại là một mosaic** ghép từ nhiều mảnh ảnh gốc khác nhaunhau, đúng như tham số `mosaic=1.0` mô tả. Ba bằng chứng nhìn thấy trực tiếp:

- **Mosaic thật sự xảy ra:** nhiều ô có 3–4 mảnh ảnh khác nhau ghép lại (ví dụ ô góc trên-trái có cả người mặc áo màu lẫn công trường sắt thép cùng khung).
- **Lật ngang (`fliplr=0.5`):** một số ô rõ ràng bị lật gương — dễ thấy ở các dòng chữ trên biển hiệu bị đảo ngược trong vài mảnh ghép.
- **Nhãn đã theo đúng ảnh đã biến đổi:** hộp màu xanh dương (nhãn `0` = helmet) và xanh lá (nhãn `1` = head) vẫn bám đúng vị trí vật thể **sau khi** ảnh đã bị mosaic/lật/co giãn — chứng tỏ pipeline augmentation của ultralytics tự động biến đổi nhãn đồng bộ với ảnh, không cần code tự viết thêm.

Đây là bằng chứng trực quan trả lời đúng câu hỏi "ảnh mà mô hình nhìn thấy lúc train là ảnh gì", không phải ảnh gốc 416×416 sạch sẽ, mà là một mảnh ghép biến dạng liên tục.

In [5]:
# ---- Đường cong huấn luyện: đọc từ results.csv do ultralytics ghi ra ----
res_csv = RUNS_DIR / RUN_BASE / "results.csv"
hist = pd.read_csv(res_csv)
hist.columns = [c.strip() for c in hist.columns]

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# (a) các thành phần loss
for col, lbl in [("train/box_loss", "box (train)"), ("train/cls_loss", "cls (train)"),
                 ("train/dfl_loss", "dfl (train)")]:
    if col in hist: axes[0].plot(hist["epoch"], hist[col], label=lbl)
for col, lbl in [("val/box_loss", "box (val)"), ("val/cls_loss", "cls (val)")]:
    if col in hist: axes[0].plot(hist["epoch"], hist[col], ls="--", label=lbl)
axes[0].set_title("(a) Đường cong mất mát"); axes[0].set_xlabel("epoch")
axes[0].set_ylabel("loss"); axes[0].legend(fontsize=8)

# (b) mAP trên tập val theo epoch
for col, lbl in [("metrics/mAP50(B)", "mAP@0.5"),
                 ("metrics/mAP50-95(B)", "mAP@0.5:0.95")]:
    if col in hist: axes[1].plot(hist["epoch"], hist[col], label=lbl, lw=2)
best_ep = int(hist["metrics/mAP50-95(B)"].idxmax()) + 1
axes[1].axvline(best_ep, color="crimson", ls=":",
                label=f"best epoch = {best_ep}")
axes[1].set_title("(b) mAP trên tập val"); axes[1].set_xlabel("epoch")
axes[1].set_ylabel("mAP"); axes[1].legend(fontsize=8)

# (c) precision / recall
for col, lbl in [("metrics/precision(B)", "precision"), ("metrics/recall(B)", "recall")]:
    if col in hist: axes[2].plot(hist["epoch"], hist[col], label=lbl, lw=2)
axes[2].set_title("(c) Precision / Recall trên val"); axes[2].set_xlabel("epoch")
axes[2].legend(fontsize=8)

plt.savefig(ARTIFACT_DIR / "fig05_training_curves.png", dpi=150, bbox_inches="tight")
plt.show()

print(f"Epoch tốt nhất: {best_ep} / {len(hist)}")
print(f"mAP@0.5 (val) tốt nhất     : {hist['metrics/mAP50(B)'].max():.4f}")
print(f"mAP@0.5:0.95 (val) tốt nhất: {hist['metrics/mAP50-95(B)'].max():.4f}")

<Figure size 1650x440 with 3 Axes>

Epoch tốt nhất: 69 / 80
mAP@0.5 (val) tốt nhất     : 0.6270
mAP@0.5:0.95 (val) tốt nhất: 0.4116


`artifacts/fig05_training_curves.png`

**Panel (a) — đây là phát hiện quan trọng nhất của cả notebook.** `train/box_loss` (xanh dương) giảm đều đặn suốt 80 epoch, xuống gần 1,0. Nhưng `val/box_loss` (đỏ nét đứt) lại **không giảm theo** — nó chạm đáy khoảng epoch 10–15 rồi đi ngang, thậm chí hơi nhích lên, quanh mức 1,25. Đây **chính xác** là dấu hiệu quá khớp (overfitting) mà note markdown ngay dưới đã cảnh báo trước: mô hình tiếp tục học tốt hơn trên tập train nhưng không còn cải thiện khả năng định vị hộp trên tập val. `cls_loss` thì ngược lại — train và val bám khá sát nhau, và cả hai đều giảm mạnh thêm ở 10 epoch cuối, đúng thời điểm `close_mosaic=10` tắt mosaic (ảnh "thật" hơn, dễ phân loại lớp hơn).

**Panel (b).** mAP@0.5 tăng nhanh trong 10 epoch đầu (từ ~0,51 lên ~0,60), sau đó tăng chậm dần và **bão hoà** quanh 0,62–0,63 từ khoảng epoch 50 trở đi. `patience=25` không kích hoạt vì mô hình vẫn nhích lên rất chậm suốt tới epoch 69 — đúng ngưỡng cho phép, không bị dừng sớm.

**Panel (c).** Recall tăng dần đều từ ~0,45 lên ~0,60. Precision thì có ba đợt **sụt đột ngột** xuống còn ~0,60 (quanh epoch 27–38) và một đợt ở epoch ~58, trước khi phục hồi về ~0,95. Đây là dao động bất thường đáng ghi vào phần *Hạn chế* — có thể do một vài epoch trúng phải tổ hợp mosaic khó, hoặc bất ổn tạm thời trong lịch trình learning rate. Vì epoch tốt nhất (69) nằm sau các đợt sụt này và không bị ảnh hưởng, kết quả cuối cùng vẫn đáng tin — nhưng đường cong này không "mượt" như panel (b), nên không nên dùng riêng lẻ để đánh giá độ ổn định.

> **Cần đọc gì ở hình trên khi viết báo cáo?** Nếu `val/box_loss` chạm đáy rồi đi lên trong khi `train/box_loss` vẫn giảm → mô hình bắt đầu quá khớp, và `patience=40` sẽ dừng sớm. Nếu cả hai vẫn đang giảm ở epoch cuối → còn dư địa, nên nói rõ trong phần *Hạn chế* rằng kết quả báo cáo là dưới ngân sách 150 epoch chứ không phải hội tụ hoàn toàn.

## 3. Đánh giá trên tập test

**Nhắc lại nghĩa của các chỉ số** (viết vào mục *Cơ sở lý thuyết* của báo cáo):

- **IoU** giữa hộp dự đoán $B_p$ và hộp thật $B_g$: $\mathrm{IoU} = \dfrac{|B_p \cap B_g|}{|B_p \cup B_g|}$.
- Một dự đoán được tính là **TP** nếu đúng lớp *và* IoU với một hộp thật chưa bị ghép $\ge$ ngưỡng.
- **AP** của một lớp = diện tích dưới đường precision–recall của lớp đó; **mAP** = trung bình AP trên các lớp.
- **mAP@0.5** dùng đúng một ngưỡng IoU = 0.5 → khoan dung với sai lệch định vị.
- **mAP@0.5:0.95** trung bình trên 10 ngưỡng IoU từ 0.5 đến 0.95 (bước 0.05) → **phạt nặng việc định vị lệch**. Khoảng cách giữa hai con số này chính là thước đo "mô hình định vị chính xác đến mức nào", và ta sẽ khai thác nó ở phần phân tích lỗi.

Đánh giá dùng `conf=0.001` (rất thấp) vì mAP theo định nghĩa là tích phân trên **toàn bộ** đường PR, cắt bớt ở ngưỡng cao sẽ cụt đuôi đường cong và làm mAP giảm giả tạo.

In [6]:
DEFAULT_CONF, DEFAULT_IOU = 0.001, 0.7

results = {}
for split in ["val", "test"]:
    m = model.val(data=str(DATA_YAML), split=split, imgsz=BASE_IMGSZ,
                  conf=DEFAULT_CONF, iou=DEFAULT_IOU, batch=32, device=DEVICE,
                  plots=True, save_json=False,
                  project=str(RUNS_DIR), name=f"{RUN_BASE}_eval_{split}",
                  exist_ok=True, verbose=False)
    results[split] = m
    d = metrics_from_ultralytics(m)
    print(f"[{split:>4}] mAP@0.5 = {d['mAP50']:.4f} | mAP@0.5:0.95 = {d['mAP50_95']:.4f} "
          f"| P = {d['precision']:.4f} | R = {d['recall']:.4f}")
    log_run(stage="val", run_id=RUN_BASE, model="yolov8n", dataset="hardhat-5k",
            split=split, imgsz=BASE_IMGSZ, epochs=COMMON["epochs"],
            batch=COMMON["batch"], seed=SEED, conf=DEFAULT_CONF, iou_nms=DEFAULT_IOU,
            train_time_min=round(train_min, 1) if train_min else None,
            notes="baseline fine-tune từ COCO", **d)

Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
Model summary (fused): 168 layers, 3,006,233 parameters, 0 gradients, 8.1 GFLOPs


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621      0.582      0.627      0.412
Speed: 0.2ms preprocess, 0.6ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80_eval_val
[ val] mAP@0.5 = 0.6270 | mAP@0.5:0.95 = 0.4117 | P = 0.6215 | R = 0.5821
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/test... 749 images, 0 backgrounds

val: New cache created: /home/lablee/Documents/wm/projectdl/data/yolo/labels/test.cache



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        749       3852      0.631      0.616      0.629      0.413
Speed: 0.1ms preprocess, 0.6ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80_eval_test
[test] mAP@0.5 = 0.6289 | mAP@0.5:0.95 = 0.4132 | P = 0.6307 | R = 0.6157


In [7]:
# ---- Bảng chỉ số theo từng lớp trên tập TEST (bảng chính của báo cáo) ----
pc = per_class_table(results["test"], CLASS_NAMES)
pc["n_test_boxes"] = [int((pd.read_parquet(ARTIFACT_DIR / "annotations.parquet")
                           .query("split == 'test' and `class` == @c")).shape[0])
                      for c in CLASS_NAMES]
display(pc)

overall = metrics_from_ultralytics(results["test"])
summary = pd.DataFrame([{
    "model": "YOLOv8n (fine-tune COCO)", "imgsz": BASE_IMGSZ,
    "mAP@0.5": round(overall["mAP50"], 4),
    "mAP@0.5:0.95": round(overall["mAP50_95"], 4),
    "precision": round(overall["precision"], 4),
    "recall": round(overall["recall"], 4),
    "F1": round(overall["f1"], 4),
    "ms/img (val loop)": overall.get("ms_per_img"),
}])
display(summary)

pc.to_csv(ARTIFACT_DIR / "tab05_per_class_test.csv", index=False, encoding="utf-8-sig")
summary.to_csv(ARTIFACT_DIR / "tab06_overall_test.csv", index=False, encoding="utf-8-sig")

gap = overall["mAP50"] - overall["mAP50_95"]
print(f"\nKhoảng cách mAP@0.5 − mAP@0.5:0.95 = {gap:.4f}")
print("→ Khoảng cách càng lớn thì lỗi 'định vị lệch' càng chiếm tỉ trọng cao; "
      "notebook 04 sẽ định lượng chính xác điều này.")

,class,AP50,AP50_95,precision,recall,F1,n_test_boxes
0,helmet,0.9558,0.6393,0.9157,0.9165,0.9161,2910
1,head,0.9160,0.5925,0.8812,0.8824,0.8818,859
2,person,0.0149,0.0078,0.0953,0.0482,0.0640,83


,model,imgsz,mAP@0.5,mAP@0.5:0.95,precision,recall,F1,ms/img (val loop)
0,YOLOv8n (fine-tune COCO),640,0.6289,0.4132,0.6307,0.6157,0.6231,1.117



Khoảng cách mAP@0.5 − mAP@0.5:0.95 = 0.2157
→ Khoảng cách càng lớn thì lỗi 'định vị lệch' càng chiếm tỉ trọng cao; notebook 04 sẽ định lượng chính xác điều này.


| Lớp | AP@0.5 | AP@0.5:0.95 | F1 | Số hộp test |
|---|---|---|---|---|
| helmet | **0,9558** | 0,6393 | 0,9161 | 2.910 |
| head | **0,9160** | 0,5925 | 0,8818 | 859 |
| person | **0,0149** | 0,0078 | 0,0640 | 83 |

Đúng như dự đoán ở notebook 01 (dựa trên việc `head` là lớp thiểu số và nhiều vật nhỏ nhất): `helmet > head` về AP, cả hai đều cao (>0,91). Nhưng **`person` gần như sụp đổ hoàn toàn** — AP chỉ 1,49%, thấp hơn `helmet`/`head` tới hơn 60 lần. Đây không phải "thấp hơn một chút", mà là mô hình **gần như không phát hiện được lớp này**.

**Vì sao mAP tổng (0,6289) lại thấp hơn nhiều so với trung bình cảm quan của helmet/head (~0,94)?** Vì mAP là **trung bình cộng đơn giản trên 3 lớp** (macro-average), không có trọng số theo số lượng hộp. Lớp `person` chỉ chiếm 83/3.852 = 2,2% số hộp trong tập test, nhưng vẫn được tính **1/3 trọng số** trong mAP tổng — kéo tụt điểm rất mạnh dù ảnh hưởng thực tế trong triển khai (tỉ lệ ảnh có người toàn thân) là nhỏ. Đây là điểm cần giải thích rõ trong báo cáo, nếu không người đọc dễ hiểu lầm "mô hình chỉ đạt 63% độ chính xác" trong khi thực chất 2 trong 3 lớp đạt trên 90%.

**Khoảng cách mAP@0.5 − mAP@0.5:0.95 = 0,2157** — khá lớn. Với `helmet`/`head`, khoảng cách riêng từng lớp là 0,32 và 0,32 (0,956→0,639 và 0,916→0,593): mô hình **tìm đúng vị trí vật thể nhưng vẽ hộp không thật khít**. Đây là manh mối quan trọng cho notebook 04 — dự đoán trước: phần lớn lỗi sẽ là *định vị lệch*, không phải *nhầm lớp*.

### Đường precision–recall cho từng lớp

Ultralytics đã tự lưu `PR_curve.png` trong thư mục eval, nhưng ta vẽ lại thủ công để **kiểm soát được hình đưa vào báo cáo** (chú thích tiếng Việt, đánh dấu điểm làm việc thực tế).

In [8]:
def plot_pr_curves(metrics, class_names, title, out_png):
    """Vẽ PR curve từng lớp từ đối tượng metrics của ultralytics."""
    curves = list(getattr(metrics, "curves", []))
    cres = list(getattr(metrics, "curves_results", []))
    idx = next((i for i, n in enumerate(curves) if "Precision-Recall" in n), None)
    if idx is None:
        print("Không lấy được curves_results; dùng ảnh PR_curve.png của ultralytics.")
        return None
    x, y, xlabel, ylabel = cres[idx]
    y = np.atleast_2d(np.asarray(y))
    present = [int(i) for i in metrics.box.ap_class_index]

    fig, ax = plt.subplots(figsize=(6.5, 5.5))
    for row, ci in enumerate(present):
        name = class_names[ci]
        ap = float(metrics.box.ap50[row])
        ax.plot(x, y[row], lw=2, label=f"{name}  (AP@0.5 = {ap:.3f})")
    ax.plot(x, y.mean(axis=0), color="k", lw=2.5, ls="--",
            label=f"trung bình  (mAP@0.5 = {float(metrics.box.map50):.3f})")
    for f in [0.5, 0.7, 0.9]:                     # đường đồng mức F1
        r = np.linspace(0.01, 1, 200)
        p = f * r / (2 * r - f)
        ok = (p >= 0) & (p <= 1)
        ax.plot(r[ok], p[ok], color="grey", lw=0.7, alpha=0.5)
        if ok.any(): ax.annotate(f"F1={f}", (r[ok][-1], p[ok][-1]), fontsize=7, color="grey")
    ax.set_xlabel(xlabel or "Recall"); ax.set_ylabel(ylabel or "Precision")
    ax.set_xlim(0, 1); ax.set_ylim(0, 1.02)
    ax.set_title(title); ax.legend(loc="lower left", fontsize=8)
    plt.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.show()
    return fig

plot_pr_curves(results["test"], CLASS_NAMES,
               "Precision–Recall theo lớp (tập test, IoU = 0.5)",
               ARTIFACT_DIR / "fig06_pr_curve_test.png")

# hiển thị luôn các hình ultralytics tự sinh (ma trận nhầm lẫn, F1-conf)
eval_dir = RUNS_DIR / f"{RUN_BASE}_eval_test"
print("Các hình ultralytics đã lưu:", [p.name for p in eval_dir.glob("*.png")])

<Figure size 715x605 with 1 Axes>

Các hình ultralytics đã lưu: ['F1_curve.png', 'PR_curve.png', 'R_curve.png', 'confusion_matrix.png', 'confusion_matrix_normalized.png', 'P_curve.png']


`artifacts/fig06_pr_curve_test.png`
Đường xanh dương (`helmet`) và cam (`head`) gần như bám sát mép trên-phải của biểu đồ — precision giữ trên 0,9 cho tới tận recall ~0,85 rồi mới rơi nhanh về 0. Đường xanh lá (`person`) là **một vệt gần như nằm sát trục hoành**, gần như không nhìn thấy — đúng với AP=0,015 đã tính. Đường nét đứt đen (trung bình mAP) bị đường `person` này **kéo tụt xuống chỉ còn quanh 0,6–0,7** dù hai đường kia gần chạm đỉnh — minh hoạ trực quan cho hiệu ứng macro-average vừa giải thích ở note trên.

### Bổ sung: đã mở `confusion_matrix_normalized.png` — số liệu thật

File nằm ở `runs/yolov8n_640_e80_eval_test/confusion_matrix_normalized.png`. Ma trận có 4 lớp trên mỗi trục (`helmet`, `head`, `person`, `background`), trục **`True`** là nhãn thật, trục **`Predicted`** là dự đoán của mô hình. Ultralytics chuẩn hoá **theo cột** (mỗi cột `True=X` cộng lại đúng bằng 1,00) — nên đọc từng cột như "trong số vật thể thật thuộc lớp X, mô hình đã xử lý chúng ra sao".

| True ↓ | → helmet | → head | → person | → background (bị bỏ sót) |
|---|---|---|---|---|
| **helmet** | 0,93 | ~0 | — | 0,07 |
| **head** | **0,03** | 0,89 | — | 0,08 |
| **person** | ~0 | ~0 | 0,05 | **0,95** |
| **background** *(FP thật)* | 0,58 | 0,30 | 0,12 | — |

**Trả lời đúng câu hỏi đã đặt ra ở trên — "mô hình nhầm `head` thành `helmet` bao nhiêu phần trăm":** chỉ **3%**. Thấp hơn nhiều so với suy đoán ban đầu (dự đoán dựa trên lý luận "helmet là lớp đa số nên mô hình sẽ ngả về nó khi lưỡng lự"). Số liệu thật bác bỏ một phần dự đoán đó: **nhầm lẫn trực tiếp giữa hai lớp gần như không đáng kể.**

**Vậy vấn đề thật của `head` nằm ở đâu?** Nhìn cột `head`: 89% đúng, 3% nhầm sang `helmet`, còn **8% rơi vào hàng `background`** — nghĩa là mô hình **hoàn toàn không phát hiện ra** 8% số đầu trần đó (không tính nhầm lớp, mà là im lặng bỏ qua). Đây khớp đúng với bức tranh "bỏ sót" đã thấy nhiều lần trong notebook, không phải "nhầm lớp".

**Phát hiện quan trọng nhất của ma trận này — xác nhận bằng số liệu chính xác điều đã suy luận từ recall=0 trước đó:** cột `person` có **95% rơi vào `background`** — khớp gần như tuyệt đối với `R_person ≈ 0,0482` đã thấy ở bảng quét conf (1 − 0,95 = 0,05 ≈ 0,0482, sai lệch chỉ do làm tròn khác nhau giữa hai phép đo). Đây là bằng chứng thứ hai, độc lập với bảng quét conf, cùng khẳng định một kết luận: **`person` không phải bị nhầm lớp — nó gần như bị bỏ qua hoàn toàn** (chỉ 5% được phát hiện đúng).

**Cột `background` (True=background) — đây là các False Positive thật sự, nơi ảnh không có vật thể nào nhưng mô hình vẫn vẽ hộp:** 58% các hộp "ảo" này bị gắn nhãn `helmet`, 30% là `head`, 12% là `person`. Cần đọc đúng ý nghĩa cột này — nó **không** nói "head bị nhầm thành helmet", mà nói "khi mô hình tự bịa ra một hộp không tương ứng vật thể thật nào, nó có xu hướng gắn nhãn `helmet` nhiều nhất". Đây vẫn là bằng chứng ủng hộ phần dự đoán ban đầu (mô hình thiên về `helmet`), nhưng biểu hiện qua **hộp ảo (false alarm)**, chứ không phải qua việc **nhầm một cái đầu trần thật thành có mũ**.

**Kết luận cần sửa lại cho chính xác, đưa vào báo cáo:** *"Mô hình gần như không nhầm lẫn trực tiếp giữa `helmet` và `head` (chỉ 3%). Sai số chủ yếu đến từ hai nguồn tách biệt: (1) bỏ sót — cả `head` (8%) và đặc biệt `person` (95%) đều có tỉ lệ không phát hiện cao; (2) báo động giả thiên lệch — khi mô hình tự tin sai (vẽ hộp ở nơi không có gì), nó có xu hướng gọi tên là `helmet` (58% các trường hợp) nhiều hơn hẳn so với `head` hay `person`."* Điều này cũng củng cố thêm cho phần phân tích khoảng cách mAP@0.5 − mAP@0.5:0.95 (0,2157) đã bàn ở cell trước: vì nhầm lẫn *giữa các lớp thật* là rất nhỏ (3%), phần lớn khoảng cách đó nhiều khả năng đến từ **định vị lệch** (hộp đúng lớp nhưng không đủ khít) chứ không phải nhầm lớp — đúng như đã dự đoán, giờ có thêm bằng chứng loại trừ nguyên nhân khác.

## 4. Quét ngưỡng confidence

**Ngưỡng confidence làm gì?** Mô hình xuất ra hàng nghìn hộp ứng viên, mỗi hộp kèm một điểm tin cậy. Ngưỡng `conf` loại bỏ mọi hộp có điểm thấp hơn. Đây là **núm vặn đánh đổi precision ↔ recall**, và không có giá trị "đúng" phổ quát — nó phụ thuộc vào việc bài toán sợ bỏ sót hay sợ báo động giả hơn.

Với bài toán phát hiện người **không** đội mũ bảo hiểm, bỏ sót một cái đầu trần nguy hiểm hơn nhiều so với báo nhầm một lần → nên chọn ngưỡng thiên về **recall**.

Ta quét **7 giá trị** (yêu cầu tối thiểu 5) trên tập **val** — vì việc chọn ngưỡng là một quyết định dựa trên dữ liệu, không được phép làm trên test.

In [9]:
CONF_GRID = [0.001, 0.05, 0.10, 0.25, 0.40, 0.55, 0.70]

rows = []
for c in CONF_GRID:
    m = model.val(data=str(DATA_YAML), split="val", imgsz=BASE_IMGSZ,
                  conf=c, iou=DEFAULT_IOU, batch=32, device=DEVICE, plots=False,
                  project=str(RUNS_DIR), name="sweep_conf", exist_ok=True, verbose=False)
    d = metrics_from_ultralytics(m)
    d.update({"conf": c})
    # P/R theo từng lớp để thấy lớp hiếm phản ứng khác lớp phổ biến
    idx = [int(i) for i in m.box.ap_class_index]
    for ci, name in enumerate(CLASS_NAMES):
        d[f"R_{name}"] = round(float(m.box.r[idx.index(ci)]), 4) if ci in idx else np.nan
    rows.append(d)
    log_run(stage="sweep_conf", run_id=RUN_BASE, model="yolov8n", dataset="hardhat-5k",
            split="val", imgsz=BASE_IMGSZ, seed=SEED, conf=c, iou_nms=DEFAULT_IOU,
            notes="quét ngưỡng confidence", **{k: v for k, v in d.items() if k != "conf"})
    print(f"conf={c:<6} P={d['precision']:.4f} R={d['recall']:.4f} "
          f"F1={d['f1']:.4f} mAP50={d['mAP50']:.4f}")

conf_df = pd.DataFrame(rows)[
    ["conf", "precision", "recall", "f1", "mAP50", "mAP50_95"] +
    [f"R_{n}" for n in CLASS_NAMES]].round(4)
conf_df.to_csv(ARTIFACT_DIR / "tab07_conf_sweep.csv", index=False, encoding="utf-8-sig")
display(conf_df)

Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.621      0.582      0.627      0.412
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.5ms postprocess per image
conf=0.001  P=0.6215 R=0.5821 F1=0.6011 mAP50=0.6270
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621      0.582      0.627      0.432
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.4ms postprocess per image
conf=0.05   P=0.6215 R=0.5821 F1=0.6011 mAP50=0.6270
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.621      0.582      0.627      0.435
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.4ms postprocess per image
conf=0.1    P=0.6215 R=0.5821 F1=0.6011 mAP50=0.6266
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.621      0.582      0.619      0.434
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 1.1ms postprocess per image


conf=0.25   P=0.6215 R=0.5821 F1=0.6011 mAP50=0.6195
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.621      0.583      0.614      0.434
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.3ms postprocess per image
conf=0.4    P=0.6214 R=0.5827 F1=0.6014 mAP50=0.6145
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.632       0.56      0.604       0.43
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.3ms postprocess per image
conf=0.55   P=0.6325 R=0.5603 F1=0.5942 mAP50=0.6038
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.648      0.499      0.576       0.42
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.3ms postprocess per image
conf=0.7    P=0.6483 R=0.4989 F1=0.5639 mAP50=0.5758


,conf,precision,recall,f1,mAP50,mAP50_95,R_helmet,R_head,R_person
0,0.001,0.6215,0.5821,0.6011,0.6270,0.4117,0.8949,0.8513,0.0
1,0.050,0.6215,0.5821,0.6011,0.6270,0.4323,0.8949,0.8513,0.0
2,0.100,0.6215,0.5821,0.6011,0.6266,0.4354,0.8949,0.8513,0.0
3,0.250,0.6215,0.5821,0.6011,0.6195,0.4344,0.8949,0.8513,0.0
4,0.400,0.6214,0.5827,0.6014,0.6145,0.4341,0.8959,0.8523,0.0
5,0.550,0.6325,0.5603,0.5942,0.6038,0.4303,0.8650,0.8158,0.0
6,0.700,0.6483,0.4989,0.5639,0.5758,0.4198,0.7853,0.7114,0.0


Bảng đầy đủ:

| conf | precision | recall | F1 | mAP50 | R_helmet | R_head | R_person |
|---|---|---|---|---|---|---|---|
| 0,001 | 0,6215 | 0,5821 | 0,6011 | 0,6270 | 0,8949 | 0,8513 | **0,0** |
| 0,05 | 0,6215 | 0,5821 | 0,6011 | 0,6270 | 0,8949 | 0,8513 | **0,0** |
| 0,10 | 0,6215 | 0,5821 | 0,6011 | 0,6266 | 0,8949 | 0,8513 | **0,0** |
| 0,25 | 0,6215 | 0,5821 | 0,6011 | 0,6195 | 0,8949 | 0,8513 | **0,0** |
| 0,40 | 0,6214 | 0,5827 | 0,6014 | 0,6145 | 0,8959 | 0,8523 | **0,0** |
| 0,55 | 0,6325 | 0,5603 | 0,5942 | 0,6038 | 0,8650 | 0,8158 | **0,0** |
| 0,70 | 0,6483 | 0,4989 | 0,5639 | 0,5758 | 0,7853 | 0,7114 | **0,0** |

Điều đáng chú ý nhất — không phải xu hướng tổng, mà **cột `R_person`: đúng bằng 0,0 ở cả 7 giá trị conf**, kể cả khi ngưỡng thấp nhất (0,001, gần như giữ mọi hộp mô hình xuất ra). Đây là bằng chứng mạnh hơn hẳn con số AP=0,0149 đã thấy: **không phải mô hình phát hiện `person` kém, mà gần như không phát hiện được cái nào cả trên toàn bộ tập val**, bất kể nới lỏng ngưỡng tin cậy tới đâu. Nguyên nhân không nằm ở ngưỡng, mà ở chính mô hình/dữ liệu huấn luyện (chỉ 562 hộp `person` trong tập train, quá ít).

Với `helmet`/`head`: recall giữ nguyên gần như không đổi từ conf=0,001 đến 0,25 (0,8949 / 0,8513), rồi mới bắt đầu giảm rõ rệt sau conf=0,4. Nghĩa là trong khoảng conf∈[0; 0,25], việc hạ ngưỡng không thêm được hộp đúng nào — các hộp bị lọc ra ở khoảng này toàn là hộp sai (điểm tin cậy thấp và đúng là nhiễu).

In [10]:
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].plot(conf_df["conf"], conf_df["precision"], "o-", label="Precision", lw=2)
axes[0].plot(conf_df["conf"], conf_df["recall"], "s-", label="Recall", lw=2)
axes[0].plot(conf_df["conf"], conf_df["f1"], "^--", label="F1", lw=2)
best_i = conf_df["f1"].idxmax()
axes[0].axvline(conf_df.loc[best_i, "conf"], color="crimson", ls=":",
                label=f"F1 tốt nhất @ conf={conf_df.loc[best_i,'conf']}")
axes[0].set_title("(a) P / R / F1 theo ngưỡng confidence")
axes[0].set_xlabel("conf"); axes[0].legend(fontsize=8)

axes[1].plot(conf_df["conf"], conf_df["mAP50"], "o-", label="mAP@0.5", lw=2)
axes[1].plot(conf_df["conf"], conf_df["mAP50_95"], "s-", label="mAP@0.5:0.95", lw=2)
axes[1].set_title("(b) mAP theo ngưỡng confidence")
axes[1].set_xlabel("conf"); axes[1].legend(fontsize=8)

for n in CLASS_NAMES:
    axes[2].plot(conf_df["conf"], conf_df[f"R_{n}"], "o-", label=n, lw=2)
axes[2].set_title("(c) Recall theo lớp"); axes[2].set_xlabel("conf")
axes[2].set_ylabel("recall"); axes[2].legend(fontsize=8)

plt.savefig(ARTIFACT_DIR / "fig07_conf_sweep.png", dpi=150, bbox_inches="tight")
plt.show()

<Figure size 1650x440 with 3 Axes>

`artifacts/fig07_conf_sweep.png`
Panel (c) cho thấy rõ nhất: đường xanh lá (`person`) là **một đường phẳng dính chặt vào trục hoành, đúng bằng 0 suốt toàn bộ trục conf** — hình ảnh trực quan của phát hiện quan trọng nhất vừa nêu ở cell trên.

Panel (a): precision (xanh dương) giữ phẳng tới conf=0,4 rồi mới tăng dần; recall (cam) giữ phẳng rồi giảm mạnh sau 0,4; F1 (xanh lá, nét đứt) gần như phẳng tuyệt đối từ 0 đến 0,4 rồi mới đi xuống. Vạch đỏ đánh dấu "F1 tốt nhất @ conf=0,4" — nhưng nhìn đường F1 thì thấy **F1 gần như không đổi trong cả khoảng 0 đến 0,4** (chênh chưa tới 0,001), nên nói "conf=0,4 là tối ưu" hơi cường điệu; chính xác hơn là "bất kỳ giá trị nào trong [0; 0,4] đều cho hiệu năng tương đương, và 0,4 chỉ là điểm cao nhất theo đúng 4 chữ số thập phân".

Panel (b): mAP@0,5 giảm dần đều theo conf tăng — đúng hiện tượng "cắt cụt đuôi đường PR" đã giải thích ở note markdown ngay dưới cell này.

> **Một điểm tinh tế phải nêu trong báo cáo** (rất dễ ăn điểm phần phân tích): ở hình (b), mAP **giảm** khi tăng `conf`. Điều này **không** có nghĩa là ngưỡng cao làm mô hình tệ đi. mAP là diện tích dưới đường PR; nâng `conf` cắt cụt phần đuôi recall cao của đường cong nên diện tích tất nhiên nhỏ đi. Nói cách khác: **mAP phải được đo ở `conf` rất thấp**, còn `conf` là tham số triển khai, chỉ nên chọn qua F1 hoặc qua yêu cầu nghiệp vụ — hai việc này hoàn toàn khác nhau và không được lẫn lộn.

## 5. Quét ngưỡng NMS (IoU threshold)

**Non-Maximum Suppression** hoạt động như sau: sắp các hộp cùng lớp theo điểm tin cậy giảm dần; lấy hộp điểm cao nhất, loại mọi hộp còn lại có IoU với nó vượt ngưỡng `iou_nms`; lặp lại với các hộp còn sót.

Đánh đổi:
- `iou_nms` **thấp** (ví dụ 0.3) → NMS "hung hăng", gộp mạnh → giảm phát hiện thừa, **nhưng** hai người đứng sát nhau sẽ bị gộp làm một → tăng bỏ sót.
- `iou_nms` **cao** (ví dụ 0.9) → hầu như không gộp → giữ được vật thể chồng lấn, **nhưng** một vật thể sinh ra nhiều hộp trùng → tăng phát hiện thừa.

Bộ dữ liệu này có nhiều cảnh đông người, đầu che nhau → ta kỳ vọng ngưỡng cao có lợi hơn. Quét **7 giá trị**.

In [11]:
IOU_GRID = [0.30, 0.45, 0.50, 0.60, 0.70, 0.80, 0.90]

rows = []
for iou in IOU_GRID:
    m = model.val(data=str(DATA_YAML), split="val", imgsz=BASE_IMGSZ,
                  conf=DEFAULT_CONF, iou=iou, batch=32, device=DEVICE, plots=False,
                  project=str(RUNS_DIR), name="sweep_iou", exist_ok=True, verbose=False)
    d = metrics_from_ultralytics(m); d["iou_nms"] = iou
    rows.append(d)
    log_run(stage="sweep_iou", run_id=RUN_BASE, model="yolov8n", dataset="hardhat-5k",
            split="val", imgsz=BASE_IMGSZ, seed=SEED, conf=DEFAULT_CONF,
            notes="quét ngưỡng NMS", **d)
    print(f"iou_nms={iou:<5} mAP50={d['mAP50']:.4f} mAP50-95={d['mAP50_95']:.4f} "
          f"P={d['precision']:.4f} R={d['recall']:.4f}")

iou_df = pd.DataFrame(rows)[["iou_nms", "precision", "recall", "f1",
                             "mAP50", "mAP50_95"]].round(4)
iou_df.to_csv(ARTIFACT_DIR / "tab08_nms_sweep.csv", index=False, encoding="utf-8-sig")
display(iou_df)

Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.623      0.581      0.628      0.415
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.4ms postprocess per image
iou_nms=0.3   mAP50=0.6279 mAP50-95=0.4155 P=0.6228 R=0.5811
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.623      0.582      0.628      0.414
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.8ms postprocess per image
iou_nms=0.45  mAP50=0.6285 mAP50-95=0.4144 P=0.6229 R=0.5816
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.622      0.582      0.629      0.414
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.5ms postprocess per image
iou_nms=0.5   mAP50=0.6286 mAP50-95=0.4139 P=0.6225 R=0.5816
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.582      0.628      0.413
Speed: 0.1ms preprocess, 0.6ms inference, 0.0ms loss, 0.7ms postprocess per image
iou_nms=0.6   mAP50=0.6283 mAP50-95=0.4130 P=0.6224 R=0.5818
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.621      0.582      0.627      0.412
Speed: 0.2ms preprocess, 0.5ms inference, 0.0ms loss, 2.2ms postprocess per image
iou_nms=0.7   mAP50=0.6270 mAP50-95=0.4117 P=0.6215 R=0.5821
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.619      0.582      0.624      0.411
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.4ms postprocess per image
iou_nms=0.8   mAP50=0.6236 mAP50-95=0.4107 P=0.6189 R=0.5822
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.603      0.562      0.611      0.406
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.6ms postprocess per image
iou_nms=0.9   mAP50=0.6106 mAP50-95=0.4058 P=0.6033 R=0.5616


,iou_nms,precision,recall,f1,mAP50,mAP50_95
0,0.30,0.6228,0.5811,0.6012,0.6279,0.4155
1,0.45,0.6229,0.5816,0.6015,0.6285,0.4144
2,0.50,0.6225,0.5816,0.6014,0.6286,0.4139
3,0.60,0.6224,0.5818,0.6014,0.6283,0.4130
4,0.70,0.6215,0.5821,0.6011,0.6270,0.4117
5,0.80,0.6189,0.5822,0.6000,0.6236,0.4107
6,0.90,0.6033,0.5616,0.5817,0.6106,0.4058


| iou_nms | precision | recall | F1 | mAP50 | mAP50_95 |
|---|---|---|---|---|---|
| 0,30 | 0,6228 | 0,5811 | 0,6012 | 0,6279 | 0,4155 |
| 0,45 | 0,6229 | 0,5816 | 0,6015 | 0,6285 | 0,4144 |
| 0,50 | 0,6225 | 0,5816 | 0,6014 | 0,6286 | 0,4139 |
| 0,60 | 0,6224 | 0,5818 | 0,6014 | 0,6283 | 0,4130 |
| 0,70 | 0,6215 | 0,5821 | 0,6011 | 0,6270 | 0,4117 |
| 0,80 | 0,6189 | 0,5822 | 0,6000 | 0,6236 | 0,4107 |
| 0,90 | 0,6033 | 0,5616 | 0,5817 | 0,6106 | 0,4058 |

Đọc theo hàng: từ 0,30 đến 0,80 mọi chỉ số **gần như đứng yên** (mAP50 dao động trong khoảng hẹp 0,624–0,629). Chỉ tới **0,90** mới thấy sụt rõ rệt ở mọi cột — precision giảm từ 0,619 xuống 0,603, recall từ 0,582 xuống 0,562. Kết luận ngược lại với suy đoán ban đầu ở note markdown phía trên (dự đoán bộ dữ liệu đông người sẽ khiến NMS rất nhạy): thực tế **vùng an toàn rất rộng** (0,3 đến 0,8), chỉ khi nới lỏng NMS đến gần như tắt hẳn (0,9 — gần như không loại bỏ gì) thì hiệu năng mới sụp. Đây là kết luận đáng tin cậy hơn hẳn so với một "điểm tối ưu mong manh".

In [12]:
fig, axes = plt.subplots(1, 2, figsize=(11, 4))
axes[0].plot(iou_df["iou_nms"], iou_df["mAP50"], "o-", lw=2, label="mAP@0.5")
axes[0].plot(iou_df["iou_nms"], iou_df["mAP50_95"], "s-", lw=2, label="mAP@0.5:0.95")
b = iou_df["mAP50_95"].idxmax()
axes[0].axvline(iou_df.loc[b, "iou_nms"], color="crimson", ls=":",
                label=f"tốt nhất @ {iou_df.loc[b,'iou_nms']}")
axes[0].set_xlabel("ngưỡng IoU của NMS"); axes[0].set_ylabel("mAP")
axes[0].set_title("(a) mAP theo ngưỡng NMS"); axes[0].legend(fontsize=8)

axes[1].plot(iou_df["iou_nms"], iou_df["precision"], "o-", lw=2, label="Precision")
axes[1].plot(iou_df["iou_nms"], iou_df["recall"], "s-", lw=2, label="Recall")
axes[1].set_xlabel("ngưỡng IoU của NMS")
axes[1].set_title("(b) Đánh đổi P/R theo ngưỡng NMS"); axes[1].legend(fontsize=8)
plt.savefig(ARTIFACT_DIR / "fig08_nms_sweep.png", dpi=150, bbox_inches="tight")
plt.show()

<Figure size 1210x440 with 2 Axes>

`artifacts/fig08_nms_sweep.png`. 
Cả hai panel đều cho thấy hình dạng giống nhau: **một đoạn phẳng dài** từ 0,3 đến 0,8, rồi một **cú rơi dốc đứng** chỉ ở điểm cuối cùng (0,9). Đây là bằng chứng hình ảnh xác nhận đúng điều vừa đọc ở bảng số: hiệu năng của mô hình **không nhạy cảm** với lựa chọn `iou_nms` trong một dải rất rộng, và chỉ sụp đổ khi NMS gần như bị vô hiệu hoá hoàn toàn. Kết luận cho báo cáo: ngưỡng mặc định 0,7 mà ultralytics dùng là lựa chọn an toàn, không cần tinh chỉnh cẩn thận cho bộ dữ liệu này.

### Bản đồ nhiệt hai chiều `conf` × `iou_nms`

Hai ngưỡng này không độc lập. Một lưới 2D cho thấy vùng cấu hình tốt rộng hay hẹp — nếu vùng tối ưu rất hẹp thì kết luận "cấu hình X là tốt nhất" rất mong manh và cần nói rõ điều đó.

In [13]:
CONF_2D = [0.05, 0.15, 0.25, 0.40, 0.55]
IOU_2D  = [0.40, 0.55, 0.70, 0.85]

grid = np.zeros((len(CONF_2D), len(IOU_2D)))
for i, c in enumerate(CONF_2D):
    for j, iou in enumerate(IOU_2D):
        m = model.val(data=str(DATA_YAML), split="val", imgsz=BASE_IMGSZ,
                      conf=c, iou=iou, batch=32, device=DEVICE, plots=False,
                      project=str(RUNS_DIR), name="sweep_2d", exist_ok=True, verbose=False)
        d = metrics_from_ultralytics(m)
        grid[i, j] = d["f1"]
        log_run(stage="sweep_2d", run_id=RUN_BASE, model="yolov8n", split="val",
                imgsz=BASE_IMGSZ, seed=SEED, conf=c, iou_nms=iou,
                notes="lưới 2D conf x iou", **d)

fig, ax = plt.subplots(figsize=(6, 4.5))
im = ax.imshow(grid, cmap="viridis", aspect="auto")
ax.set_xticks(range(len(IOU_2D)), IOU_2D); ax.set_yticks(range(len(CONF_2D)), CONF_2D)
ax.set_xlabel("ngưỡng IoU của NMS"); ax.set_ylabel("ngưỡng confidence")
ax.set_title("F1 trên tập val theo (conf, iou_nms)")
for i in range(len(CONF_2D)):
    for j in range(len(IOU_2D)):
        ax.text(j, i, f"{grid[i,j]:.3f}", ha="center", va="center",
                color="white" if grid[i, j] < grid.max() * 0.97 else "black", fontsize=9)
plt.colorbar(im, ax=ax, label="F1")
plt.savefig(ARTIFACT_DIR / "fig09_conf_iou_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()

bi, bj = np.unravel_index(grid.argmax(), grid.shape)
BEST_CONF, BEST_IOU = CONF_2D[bi], IOU_2D[bj]
print(f"Cấu hình triển khai tốt nhất theo F1 trên val: conf={BEST_CONF}, iou_nms={BEST_IOU} "
      f"(F1={grid[bi,bj]:.4f})")
json.dump({"conf": BEST_CONF, "iou": BEST_IOU},
          open(ARTIFACT_DIR / "best_thresholds.json", "w"))

Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.623      0.582      0.628      0.434
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.3ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.582      0.628      0.434
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621      0.582      0.627      0.432
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.616       0.58      0.622      0.426
Speed: 0.1ms preprocess, 0.6ms inference, 0.0ms loss, 0.9ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.623      0.582      0.624      0.436
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.5ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.582      0.624      0.436
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.3ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.621      0.582      0.624      0.436
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.5ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.616       0.58       0.62      0.431
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.4ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.623      0.582      0.619      0.435
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.582       0.62      0.435
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.3ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.621      0.582      0.619      0.434
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   0%|     

WARNING ⚠️ NMS time limit 3.600s exceeded


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95):   4%|▍    

WARNING ⚠️ NMS time limit 3.600s exceeded


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.616      0.576      0.614       0.43
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 13.3ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.582      0.614      0.434
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.582      0.614      0.434
Speed: 0.1ms preprocess, 0.6ms inference, 0.0ms loss, 0.9ms postprocess per image


Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.621      0.583      0.614      0.434
Speed: 0.1ms preprocess, 0.6ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.616       0.58      0.613      0.433
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.4ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.634      0.559      0.604       0.43
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.4ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.634       0.56      0.604       0.43
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.632       0.56      0.604       0.43
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.9ms postprocess per image
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)



val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.628       0.56      0.603       0.43
Speed: 0.3ms preprocess, 0.5ms inference, 0.0ms loss, 1.0ms postprocess per image


<Figure size 660x495 with 2 Axes>

Cấu hình triển khai tốt nhất theo F1 trên val: conf=0.4, iou_nms=0.4 (F1=0.6016)


Đây là điểm dễ mất điểm nếu trả lời máy móc. Cần trình bày như sau:

**Anchor-based (YOLOv2 → v5, Faster R-CNN — đúng phần được dạy ở Bài 6, tr.48-51):** mỗi ô lưới gắn sẵn $k$ hộp mẫu (anchor) với tỉ lệ khung định trước. Mạng không hồi quy toạ độ tuyệt đối mà hồi quy **độ lệch** so với anchor. Kích thước anchor được chọn bằng **k-means trên phân bố kích thước hộp của tập train** (Bài 6, tr.51). Nhược điểm: thêm siêu tham số, và nếu anchor không khớp phân bố dữ liệu thì hiệu năng sụt.

**Anchor-free (YOLOv8 — mô hình nhóm dùng):** đề bài chỉ định YOLOv8n, mà phiên bản này đã **bỏ hẳn anchor**. Mỗi vị trí trên feature map dự đoán trực tiếp khoảng cách từ điểm đó tới 4 cạnh của hộp. Khoảng cách không được dự đoán như một con số duy nhất mà như một **phân phối rời rạc** trên các giá trị có thể — đó là ý nghĩa của `dfl_loss` xuất hiện ở đường cong huấn luyện §2, và của tham số `reg_max` in ra ở cell dưới.

> **Ghi chú trung thực cho báo cáo.** Bài giảng dừng ở YOLOv3 (anchor-based). YOLOv8 nằm ngoài phạm vi đó, nhưng là mô hình đề bài yêu cầu. Nhóm xử lý bằng cách: (1) kiểm chứng **từ chính checkpoint** rằng mô hình không có anchor, (2) vẫn chạy k-means anchor trên dữ liệu để minh họa phần *được dạy* — anchor **sẽ** trông thế nào nếu dùng YOLOv5, và (3) không bàn sâu hơn về cơ chế gán nhãn dương/âm của YOLOv8 vì nằm ngoài kiến thức môn học.

In [14]:
det = model.model.model[-1]        # lớp Detect cuối cùng
print("Kiểu lớp Detect :", type(det).__name__)
print("Số lớp (nc)     :", det.nc)
print("Số stride       :", [int(s) for s in det.stride])
print("reg_max (DFL)   :", getattr(det, "reg_max", "n/a"))
n_anchor = getattr(det, "na", None)
print("Số anchor/vị trí:", n_anchor if n_anchor is not None else
      "không có thuộc tính anchor → mô hình là anchor-free")

# Số vị trí dự đoán (anchor point) tại từng mức đặc trưng, với ảnh 640x640
total = 0
print("\nLưới dự đoán ở ảnh 640x640:")
for s in det.stride:
    g = BASE_IMGSZ // int(s)
    total += g * g
    print(f"  stride {int(s):>2}: lưới {g}x{g} = {g*g:>6,} vị trí "
          f"→ chuyên bắt vật thể {'nhỏ' if s==8 else 'vừa' if s==16 else 'lớn'}")
print(f"  TỔNG: {total:,} hộp ứng viên trước NMS")
print("\n→ Đây chính là lý do phải có NMS: mạng luôn xuất ra hàng nghìn hộp, "
      "phần lớn là bản sao chồng lấn của cùng một vật thể.")

Kiểu lớp Detect : Detect
Số lớp (nc)     : 3
Số stride       : [8, 16, 32]
reg_max (DFL)   : 16
Số anchor/vị trí: không có thuộc tính anchor → mô hình là anchor-free

Lưới dự đoán ở ảnh 640x640:
  stride  8: lưới 80x80 =  6,400 vị trí → chuyên bắt vật thể nhỏ
  stride 16: lưới 40x40 =  1,600 vị trí → chuyên bắt vật thể vừa
  stride 32: lưới 20x20 =    400 vị trí → chuyên bắt vật thể lớn
  TỔNG: 8,400 hộp ứng viên trước NMS

→ Đây chính là lý do phải có NMS: mạng luôn xuất ra hàng nghìn hộp, phần lớn là bản sao chồng lấn của cùng một vật thể.


In [15]:
# k-means trên kích thước hộp thật: "nếu dùng YOLOv5 thì anchor sẽ ra sao?"
from scipy.cluster.vq import kmeans

ann = pd.read_parquet(ARTIFACT_DIR / "annotations.parquet")
tr = ann[ann["split"] == "train"]
wh = np.stack([tr["box_w"] / tr["img_w"] * BASE_IMGSZ,
               tr["box_h"] / tr["img_h"] * BASE_IMGSZ], axis=1)
wh = wh[(wh > 2).all(axis=1)]

np.random.seed(SEED)
centroids, _ = kmeans(wh.astype(np.float32), 9, iter=30)
centroids = centroids[np.argsort(centroids.prod(axis=1))]

fig, ax = plt.subplots(figsize=(6, 5))
ax.scatter(wh[:, 0], wh[:, 1], s=3, alpha=0.10, label="hộp thật (train)")
ax.scatter(centroids[:, 0], centroids[:, 1], s=140, marker="X", c="crimson",
           edgecolor="k", label="9 anchor từ k-means")
ax.set_xscale("log"); ax.set_yscale("log")
ax.set_xlabel("w (px @640)"); ax.set_ylabel("h (px @640)")
ax.set_title("Phân bố kích thước hộp và anchor giả định")
ax.legend(fontsize=8)
plt.savefig(ARTIFACT_DIR / "fig10_anchor_kmeans.png", dpi=150, bbox_inches="tight")
plt.show()

print("Anchor (w×h, px @640), sắp theo diện tích:")
for w, h in centroids:
    print(f"  {w:6.1f} × {h:6.1f}   (tỉ lệ w/h = {w/h:.2f})")
print("\nNhận xét để viết vào báo cáo: các anchor tập trung ở vùng nhỏ và gần vuông, "
      "phản ánh việc đối tượng chủ yếu là 'cái đầu' — hình gần vuông, kích thước nhỏ.")

<Figure size 660x550 with 1 Axes>

Anchor (w×h, px @640), sắp theo diện tích:
    25.6 ×   28.0   (tỉ lệ w/h = 0.92)
    43.0 ×   46.4   (tỉ lệ w/h = 0.93)
    61.4 ×   71.6   (tỉ lệ w/h = 0.86)
   120.6 ×   60.7   (tỉ lệ w/h = 1.99)
    87.6 ×  104.3   (tỉ lệ w/h = 0.84)
   131.2 ×  147.0   (tỉ lệ w/h = 0.89)
   241.3 ×  101.2   (tỉ lệ w/h = 2.39)
   159.0 ×  249.3   (tỉ lệ w/h = 0.64)
   275.2 ×  368.1   (tỉ lệ w/h = 0.75)

Nhận xét để viết vào báo cáo: các anchor tập trung ở vùng nhỏ và gần vuông, phản ánh việc đối tượng chủ yếu là 'cái đầu' — hình gần vuông, kích thước nhỏ.


### 6.2 IoU và NMS — minh họa trên một ảnh thật

Ta chọn một ảnh đông người trong tập test, rồi chạy suy luận với **cùng `conf` nhưng ba ngưỡng NMS khác nhau**, đặt cạnh nhau. Đây là bằng chứng trực quan cho phần §5.

In [16]:
def iou_xyxy(a, b):
    """IoU giữa hai hộp dạng [x1,y1,x2,y2]."""
    ix1, iy1 = max(a[0], b[0]), max(a[1], b[1])
    ix2, iy2 = min(a[2], b[2]), min(a[3], b[3])
    inter = max(0.0, ix2 - ix1) * max(0.0, iy2 - iy1)
    ua = ((a[2]-a[0]) * (a[3]-a[1]) + (b[2]-b[0]) * (b[3]-b[1]) - inter)
    return inter / ua if ua > 0 else 0.0

# chọn ảnh test đông đối tượng nhất
test_counts = ann[ann["split"] == "test"].groupby("stem").size().sort_values(ascending=False)
demo_stem = test_counts.index[3]
demo_img = next((YOLO_DIR / "images" / "test").glob(f"{demo_stem}.*"))
print(f"Ảnh minh họa: {demo_stem} ({test_counts.iloc[3]} đối tượng thật)")

DEMO_CONF = 0.25
fig, axes = plt.subplots(1, 3, figsize=(16, 5.5))
for ax, iou_nms in zip(axes, [0.95, 0.70, 0.30]):
    r = model.predict(source=str(demo_img), conf=DEMO_CONF, iou=iou_nms,
                      device=DEVICE, verbose=False, max_det=300)[0]
    ax.imshow(r.plot(labels=False, line_width=2)[..., ::-1])
    ax.axis("off")
    ax.set_title(f"iou_nms = {iou_nms}  →  {len(r.boxes)} hộp giữ lại", fontsize=10)
fig.suptitle(f"Ảnh hưởng của ngưỡng NMS ở cùng conf = {DEMO_CONF}", fontsize=12)
plt.savefig(ARTIFACT_DIR / "fig11_nms_effect.png", dpi=150, bbox_inches="tight")
plt.show()

Ảnh minh họa: hard_hat_workers2289 (26 đối tượng thật)


<Figure size 1760x605 with 3 Axes>

## 7. Ảnh hưởng của độ phân giải đầu vào (Yêu cầu nâng cao)

> *"Đo ảnh hưởng của độ phân giải đầu vào (416 / 640 / 960) tới mAP và FPS."*

**Cách làm sai thường gặp:** lấy mô hình đã train ở 640 rồi đem `val` ở 416 và 960. Cách này đo lẫn hai thứ: ảnh hưởng thật của độ phân giải **và** sự lệch phân bố giữa lúc train với lúc test. Kết luận rút ra sẽ không đáng tin.

**Cách làm đúng — và là cách ta làm ở đây:** **train lại** ở từng độ phân giải với **cùng seed, cùng số epoch, cùng batch-equivalent**, rồi mới so sánh. Tốn thời gian hơn nhưng đó mới là "thí nghiệm công bằng" theo đúng thang điểm.

Ba lượt train ~1–1,5 giờ trên 4090. Batch được giảm ở 960 để vừa VRAM; ta ghi rõ điều này thay vì giấu đi, vì batch size cũng ảnh hưởng nhẹ tới kết quả.

In [18]:
def measure_fps(weights, imgsz, n_warmup=30, n_iter=200, half=False):
    """Đo tốc độ suy luận thật: batch=1, đã warm-up, có đồng bộ CUDA.

    Chỉ số ultralytics in ra trong vòng val KHÔNG dùng được để báo cáo FPS vì
    nó đo theo batch lớn và bỏ qua chi phí một số bước.
    """
    m = YOLO(str(weights))
    dummy = np.random.randint(0, 255, (imgsz, imgsz, 3), dtype=np.uint8)
    for _ in range(n_warmup):
        m.predict(dummy, imgsz=imgsz, device=DEVICE, verbose=False, half=half)
    torch.cuda.synchronize()
    t0 = time.perf_counter()
    for _ in range(n_iter):
        m.predict(dummy, imgsz=imgsz, device=DEVICE, verbose=False, half=half)
    torch.cuda.synchronize()
    ms = (time.perf_counter() - t0) / n_iter * 1000
    return {"ms_per_img": round(ms, 3), "fps": round(1000 / ms, 1)}

print("Kiểm tra hàm đo tốc độ trên mô hình baseline:")
print(measure_fps(best_ckpt, BASE_IMGSZ))

Kiểm tra hàm đo tốc độ trên mô hình baseline:
{'ms_per_img': 10.143, 'fps': 98.6}


In [19]:
RES_GRID = [(416, 32), (640, 32), (960, 16)]     # (imgsz, batch) — vừa VRAM T4 16GB
res_rows = []

for imgsz, batch in RES_GRID:
    run_name = f"yolov8n_{imgsz}_e{EP}"
    ckpt = RUNS_DIR / run_name / "weights" / "best.pt"

    if not ckpt.exists():
        set_seed(SEED)
        cfg = dict(COMMON); cfg["batch"] = batch
        mm = YOLO("yolov8n.pt")
        t0 = time.time()
        mm.train(name=run_name, imgsz=imgsz, **cfg)
        tmin = (time.time() - t0) / 60
    else:
        tmin = None
        print(f"Dùng lại checkpoint có sẵn: {ckpt}")

    mdl = YOLO(str(ckpt))
    mt = mdl.val(data=str(DATA_YAML), split="test", imgsz=imgsz,
                 conf=DEFAULT_CONF, iou=DEFAULT_IOU, batch=32, device=DEVICE,
                 plots=False, project=str(RUNS_DIR),
                 name=f"{run_name}_eval_test", exist_ok=True, verbose=False)
    d = metrics_from_ultralytics(mt)
    speed = measure_fps(ckpt, imgsz)
    d.update(speed)

    idx = [int(i) for i in mt.box.ap_class_index]
    for ci, name in enumerate(CLASS_NAMES):
        d[f"AP50_{name}"] = round(float(mt.box.ap50[idx.index(ci)]), 4) if ci in idx else np.nan

    res_rows.append({"imgsz": imgsz, "batch": batch,
                     "train_time_min": round(tmin, 1) if tmin else None, **d})
    log_run(stage="resolution", run_id=run_name, model="yolov8n", dataset="hardhat-5k",
            split="test", imgsz=imgsz, epochs=COMMON["epochs"], batch=batch, seed=SEED,
            conf=DEFAULT_CONF, iou_nms=DEFAULT_IOU,
            train_time_min=round(tmin, 1) if tmin else None,
            notes="khảo sát độ phân giải", **d)
    print(f"[imgsz={imgsz}] mAP50={d['mAP50']:.4f} mAP50-95={d['mAP50_95']:.4f} "
          f"FPS={d['fps']}")

res_df = pd.DataFrame(res_rows)[
    ["imgsz", "batch", "mAP50", "mAP50_95", "precision", "recall",
     "AP50_helmet", "AP50_head", "AP50_person", "fps", "ms_per_img",
     "train_time_min"]].round(4)
res_df.to_csv(ARTIFACT_DIR / "tab09_resolution.csv", index=False, encoding="utf-8-sig")
display(res_df)

New https://pypi.org/project/ultralytics/8.4.126 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/home/lablee/Documents/wm/projectdl/configs/helmet.yaml, epochs=80, time=None, patience=25, batch=32, imgsz=416, save=True, save_period=-1, cache=False, device=0, workers=8, project=/home/lablee/Documents/wm/projectdl/runs, name=yolov8n_416_e80, exist_ok=True, pretrained=True, optimizer=SGD, verbose=False, seed=42, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agno

train: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/train.cache... 3501 images, 0 b
val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr


Plotting labels to /home/lablee/Documents/wm/projectdl/runs/yolov8n_416_e80/labels.jpg... 
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 416 train, 416 val
Using 8 dataloader workers
Logging results to /home/lablee/Documents/wm/projectdl/runs/yolov8n_416_e80
Starting training for 80 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/80      1.97G      1.603      2.143      1.269        107        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.903      0.389      0.501      0.276

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/80      2.27G      1.492      1.195      1.198         88        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.551      0.478      0.544      0.309



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/80      2.36G      1.486       1.15      1.193         74        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.893      0.463      0.525      0.302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/80      2.19G      1.504       1.14      1.202         95        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.807      0.413      0.437       0.21

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/80      2.06G      1.476      1.081      1.187        138        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.596        0.5      0.536      0.308

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/80      2.26G      1.441      1.035      1.176        132        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.572      0.478      0.531      0.311

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/80      2.32G      1.416     0.9808      1.162         92        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.873      0.452      0.506       0.29

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/80      2.46G      1.416     0.9608      1.156         71        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.916        0.5      0.564       0.34



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/80      2.37G      1.398     0.9517      1.156         49        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.917      0.474      0.546      0.325

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/80      2.15G      1.403     0.9252       1.14         63        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.916      0.513      0.579      0.334



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/80      2.42G      1.361     0.8864      1.139         65        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.911      0.504      0.562      0.341



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/80       2.3G      1.357     0.8889      1.134        124        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.916      0.506      0.571       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/80      2.31G      1.347     0.8654      1.128         75        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.577      0.563      0.584      0.358



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/80       2.3G      1.355     0.8617      1.121         84        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.925       0.52      0.582      0.356



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/80      2.41G      1.341     0.8395       1.12         72        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.922      0.532      0.581      0.349



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/80      2.25G      1.335     0.8457      1.123         95        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.937      0.524      0.584      0.359



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/80      2.38G      1.332     0.8301      1.126         84        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.923      0.524      0.586       0.35

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/80      2.26G      1.327     0.8191      1.111         63        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.932      0.515      0.581      0.357



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/80      2.37G      1.319     0.8122      1.114         68        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.921      0.542      0.596       0.37

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/80      2.44G      1.312     0.8151      1.104        128        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.927      0.521      0.581       0.36



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/80      2.46G      1.295     0.7882      1.096        117        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.928       0.52      0.581      0.349

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/80      2.42G      1.299      0.798      1.105        101        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.938      0.531      0.596      0.366



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/80      2.31G      1.288     0.7866      1.106        105        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.931      0.529      0.599      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/80      2.37G      1.276     0.7776       1.09        105        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.612      0.568      0.597      0.375



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/80      2.41G      1.273     0.7654      1.096         74        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.921      0.523      0.581      0.352

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/80      2.58G      1.297     0.7753      1.092        111        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.935      0.538      0.595      0.373



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/80      2.43G      1.269      0.761      1.092         90        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.924      0.551      0.597       0.37



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/80      2.47G      1.265     0.7528      1.091         69        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.922      0.538      0.593      0.368



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/80       2.4G      1.274     0.7527       1.09        126        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.932      0.547      0.605      0.373



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/80      2.58G       1.26     0.7501      1.082         90        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.938      0.535      0.602      0.375

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/80      2.51G      1.262     0.7425      1.085         81        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.618      0.582      0.608      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/80      2.34G      1.238     0.7294      1.075         72        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.947      0.539      0.602       0.38



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      33/80      2.48G      1.252     0.7312      1.084        115        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.933      0.554      0.608      0.382



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      34/80      2.46G      1.236     0.7206      1.069        123        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867       0.94      0.549      0.608      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      35/80      2.46G      1.229     0.7159      1.075         86        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.603      0.547      0.603       0.38

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      36/80      2.61G      1.237     0.7145      1.072         91        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.944      0.556      0.614      0.385



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      37/80      2.61G      1.229     0.7245      1.067         63        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.941      0.555      0.611      0.388



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      38/80      2.66G      1.225     0.7053      1.069        104        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.607      0.554      0.613      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      39/80      2.68G      1.223     0.6995      1.066        129        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.612      0.562      0.614      0.386



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      40/80      2.53G      1.226      0.709      1.064         72        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.609      0.555      0.614       0.39



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      41/80      2.65G      1.226     0.6932      1.066         95        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.943      0.565      0.614      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      42/80      2.71G      1.203     0.6915      1.066        110        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.678       0.56      0.618      0.392

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      43/80      2.67G      1.198     0.6753      1.057        100        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867        0.6      0.561      0.614      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      44/80      2.68G      1.198     0.6724      1.056         88        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.603      0.559       0.61      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      45/80      2.64G      1.191     0.6718      1.054         76        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.601      0.582      0.617      0.393



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      46/80      2.68G      1.188     0.6655      1.055         88        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.664      0.573      0.615      0.392

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      47/80      2.71G      1.184     0.6626      1.055        108        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.607      0.586      0.616      0.393



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      48/80       2.8G      1.178     0.6591      1.044         71        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.947      0.563      0.616      0.393



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      49/80      2.74G      1.181     0.6478      1.045        104        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.611      0.575      0.613      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      50/80      2.76G      1.174     0.6504      1.045        102        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.612      0.566      0.618      0.395



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      51/80      2.81G      1.168      0.646      1.039         64        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.612      0.567      0.616      0.395



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      52/80      2.79G      1.155     0.6362      1.044         94        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.602      0.571      0.616      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      53/80      2.82G      1.159     0.6448      1.045         71        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.604      0.567      0.615      0.392



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      54/80      2.82G      1.165     0.6419      1.041         62        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.581      0.608      0.618      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      55/80      2.65G      1.151     0.6294      1.036         76        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.609      0.564      0.616      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      56/80      3.02G      1.161     0.6294      1.035         84        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.606       0.57      0.615      0.391



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      57/80      3.06G      1.144     0.6221      1.033         66        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.615       0.56      0.614      0.394

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      58/80      2.77G      1.139     0.6204       1.03         68        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.624      0.581      0.622        0.4



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      59/80      2.68G      1.133     0.6173      1.027         45        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.617      0.559      0.618      0.395



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      60/80      2.89G      1.143     0.6213      1.033        131        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.593      0.595       0.62        0.4



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      61/80      3.01G      1.131     0.6058      1.021         97        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.609       0.57       0.62      0.398



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      62/80      2.91G      1.126     0.5956      1.026        106        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.638      0.565      0.618      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      63/80      2.41G      1.125     0.6081      1.028         75        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.61      0.569      0.619      0.401



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      64/80      2.38G      1.115     0.5969      1.019         54        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.613      0.578      0.619      0.401

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      65/80      2.04G      1.119     0.5903      1.022         95        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.59      0.593      0.617      0.398



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      66/80         2G      1.119     0.5954      1.024        108        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.619      0.563      0.618      0.399

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      67/80      2.11G      1.116     0.5958      1.023         82        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.61      0.582      0.618      0.399



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      68/80      2.16G      1.108     0.5851      1.016         87        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.596       0.62      0.399



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      69/80      2.12G      1.109     0.5835      1.014         64        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.653       0.58      0.622      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      70/80      1.95G      1.106     0.5818      1.021        124        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.616      0.567      0.618        0.4
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      71/80      2.13G      1.088     0.5152      1.026         62        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.622       0.56      0.618      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      72/80       2.1G      1.087     0.5093      1.025         56        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867       0.62      0.563      0.618      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      73/80      2.08G       1.07     0.5036      1.017         51        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.609      0.571      0.618      0.399

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      74/80      2.02G      1.078     0.5018       1.02         59        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.624      0.559      0.618      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      75/80      1.86G      1.074     0.5011      1.019         69        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.625      0.558      0.619      0.399

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      76/80      1.95G      1.068     0.4993      1.018        124        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.614      0.568      0.618      0.399

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      77/80      1.99G      1.067     0.4967      1.013         62        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.614      0.567      0.618      0.399



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      78/80      2.22G      1.066     0.4981      1.017         44        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.617      0.566      0.617        0.4



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      79/80      2.02G      1.065     0.4915      1.013         54        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.615      0.566      0.618        0.4



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      80/80      2.06G       1.07     0.4942      1.019         69        416: 100%|██████████| 110/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.616      0.565      0.618        0.4



80 epochs completed in 0.262 hours.
Optimizer stripped from /home/lablee/Documents/wm/projectdl/runs/yolov8n_416_e80/weights/last.pt, 6.2MB
Optimizer stripped from /home/lablee/Documents/wm/projectdl/runs/yolov8n_416_e80/weights/best.pt, 6.2MB

Validating /home/lablee/Documents/wm/projectdl/runs/yolov8n_416_e80/weights/best.pt...
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
Model summary (fused): 168 layers, 3,006,233 parameters, 0 gradients, 8.1 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.653       0.58      0.622      0.402
Speed: 0.0ms preprocess, 0.1ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to /home/lablee/Documents/wm/projectdl/runs/yolov8n_416_e80
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
Model summary (fused): 168 layers, 3,006,233 parameters, 0 gradients, 8.1 GFLOPs


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/test.cache... 749 images, 0 backg
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        749       3852      0.604      0.579      0.623      0.404
Speed: 0.0ms preprocess, 0.4ms inference, 0.0ms loss, 0.5ms postprocess per image


[imgsz=416] mAP50=0.6232 mAP50-95=0.4035 FPS=105.0
Dùng lại checkpoint có sẵn: /home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80/weights/best.pt
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
Model summary (fused): 168 layers, 3,006,233 parameters, 0 gradients, 8.1 GFLOPs


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/test.cache... 749 images, 0 backg
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        749       3852      0.631      0.616      0.629      0.413
Speed: 0.1ms preprocess, 0.5ms inference, 0.0ms loss, 0.3ms postprocess per image


[imgsz=640] mAP50=0.6289 mAP50-95=0.4132 FPS=256.1
New https://pypi.org/project/ultralytics/8.4.126 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/home/lablee/Documents/wm/projectdl/configs/helmet.yaml, epochs=80, time=None, patience=25, batch=16, imgsz=960, save=True, save_period=-1, cache=False, device=0, workers=8, project=/home/lablee/Documents/wm/projectdl/runs, name=yolov8n_960_e80, exist_ok=True, pretrained=True, optimizer=SGD, verbose=False, seed=42, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream

train: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/train.cache... 3501 images, 0 b
val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/val.cache... 750 images, 0 backgr


Plotting labels to /home/lablee/Documents/wm/projectdl/runs/yolov8n_960_e80/labels.jpg... 
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 960 train, 960 val
Using 8 dataloader workers
Logging results to /home/lablee/Documents/wm/projectdl/runs/yolov8n_960_e80
Starting training for 80 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/80      5.24G      1.503      2.164      1.418         58        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.887       0.47      0.541      0.306

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/80      5.44G      1.434      1.265      1.331         93        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.868      0.494      0.548      0.314

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/80      5.42G      1.435      1.203      1.324        118        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.542      0.484      0.547      0.316

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/80      5.86G      1.431      1.162      1.312         77        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.91      0.497      0.557      0.324



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/80      5.78G      1.412      1.093      1.311         90        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.893        0.5      0.555      0.335



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/80      5.46G        1.4      1.054      1.307        135        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.902      0.473      0.546       0.32



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/80      5.44G      1.386      1.006        1.3         71        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.902      0.517      0.575      0.348



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/80      6.35G      1.376     0.9653      1.286         55        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.909      0.523      0.581      0.351



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/80      5.47G      1.373     0.9555       1.29         92        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.924      0.536      0.592      0.359



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/80      5.82G      1.345     0.9022      1.276         71        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.928      0.543      0.599      0.368

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/80      5.95G      1.347     0.8945      1.283        100        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.919      0.549      0.594       0.36



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/80      5.78G      1.336      0.895      1.274         75        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.923      0.537      0.596      0.372



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/80      5.69G      1.326     0.8671      1.274         76        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.934      0.551      0.609      0.381



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/80      5.34G      1.322     0.8548      1.267        109        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.93      0.554      0.608       0.38



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/80       5.7G      1.318     0.8407      1.268        100        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.923      0.557      0.605      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/80      5.46G      1.298     0.8287       1.26         64        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.935      0.553      0.609       0.38



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/80      5.04G      1.302     0.8221       1.26         73        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.942      0.548       0.61      0.383



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/80         6G      1.305     0.8219       1.26         72        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.93      0.565      0.612       0.38



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/80      5.43G      1.286     0.8068      1.254         88        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.935      0.549      0.603      0.384



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/80      5.75G      1.282     0.8004      1.245         81        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.932      0.557      0.611      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/80      5.39G      1.293     0.8027      1.256         95        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.946      0.547      0.613      0.386



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/80      5.75G      1.274     0.7799      1.243         64        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.94      0.558       0.61      0.383



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/80      5.15G       1.27     0.7629      1.242        114        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.938      0.555      0.613      0.383



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/80      5.45G      1.263     0.7603      1.234         95        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.935      0.567      0.622      0.394



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/80      5.31G      1.272     0.7636      1.237         74        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.937      0.567      0.621      0.399



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/80      5.85G      1.266     0.7704      1.238        149        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.94      0.563      0.619      0.392



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/80      5.96G       1.26     0.7519      1.233         87        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.929      0.569      0.613      0.393



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/80      5.27G       1.25     0.7472      1.228         96        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.941      0.571      0.625        0.4



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/80      5.71G      1.237     0.7297      1.226        115        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.939      0.575      0.622      0.396



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/80      5.28G      1.244     0.7335      1.225         87        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.937      0.571      0.619      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/80      5.12G      1.243     0.7314      1.233         61        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.595      0.572      0.617      0.393



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/80       5.3G      1.233     0.7211      1.218         81        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.952      0.571       0.62      0.398



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      33/80      6.06G      1.231     0.7099      1.208        137        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.945      0.569      0.624      0.398



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      34/80      5.45G      1.226     0.7086      1.214        116        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.616      0.573      0.625      0.403



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      35/80      5.77G      1.221     0.7067      1.204         75        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.612      0.571      0.623      0.397



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      36/80      5.89G      1.214     0.7017      1.209         89        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.604      0.604      0.628      0.403



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      37/80      5.75G      1.209     0.6943      1.208         77        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.942      0.582      0.629      0.403



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      38/80      5.56G      1.209     0.6875      1.204         98        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.939      0.579      0.627      0.406



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      39/80      5.25G        1.2     0.6838      1.206         73        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.946      0.582      0.626      0.403



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      40/80      5.33G      1.197     0.6798      1.194         98        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.951      0.568      0.622      0.399



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      41/80      5.65G      1.197     0.6749      1.203        110        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.609      0.575      0.625      0.406



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      42/80      5.78G      1.194     0.6674      1.193         97        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.964      0.562      0.625      0.406



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      43/80      5.42G      1.179     0.6486      1.186        111        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.614      0.578      0.623      0.404



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      44/80      5.55G      1.171     0.6437       1.18         84        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.62      0.571      0.624      0.402



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      45/80      6.02G      1.173     0.6521      1.179         94        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.611      0.573      0.623      0.404



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      46/80      5.49G      1.174     0.6545      1.187         98        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.62      0.578      0.624      0.408



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      47/80      5.28G      1.159     0.6301       1.17         84        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.614      0.573      0.622      0.406



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      48/80      5.83G      1.157     0.6346      1.173        108        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.616      0.576      0.626      0.406



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      49/80      5.36G      1.171     0.6287      1.174         61        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.612      0.603      0.627      0.408



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      50/80      5.48G      1.154     0.6245      1.177         63        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.618       0.57      0.623      0.405



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      51/80      5.69G      1.142     0.6167      1.164         86        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.611      0.582      0.627      0.408



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      52/80      5.23G       1.14     0.6107       1.17        106        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.593      0.628      0.408



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      53/80      5.14G       1.14     0.6169      1.163        111        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.628      0.585      0.629      0.412



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      54/80      5.18G      1.127     0.6043      1.157         67        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.631      0.607      0.629       0.41



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      55/80      5.83G      1.123     0.5974      1.156        107        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.606      0.599      0.626       0.41



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      56/80      5.35G      1.122      0.593      1.151         72        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.639      0.589      0.628      0.414



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      57/80      5.12G      1.115     0.5927       1.15         81        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.954      0.577      0.627      0.409



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      58/80      5.41G      1.116     0.5881      1.147        138        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.622      0.607      0.629      0.411



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      59/80       5.2G      1.113     0.5822      1.148         90        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.633      0.587      0.628       0.41



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      60/80      4.96G      1.105     0.5708      1.141        114        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.619      0.581      0.629      0.414



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      61/80      5.45G      1.083     0.5648      1.132         94        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.621       0.58      0.626      0.411



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      62/80      5.12G      1.103     0.5675      1.137         96        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.607        0.6      0.626       0.41



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      63/80      5.58G      1.091     0.5594      1.139         78        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.624      0.577      0.626      0.412



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      64/80      5.73G      1.105     0.5655      1.133         78        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.632      0.583      0.627      0.411



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      65/80      5.79G      1.083     0.5532      1.128        103        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.606      0.594      0.626      0.411



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      66/80      5.36G      1.089     0.5595      1.135         65        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.617      0.586      0.626      0.412



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      67/80      5.13G      1.074     0.5473      1.128         60        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.61      0.598      0.628      0.413



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      68/80      6.09G      1.079     0.5572      1.126         94        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.616      0.587      0.628      0.414



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      69/80      5.04G      1.074     0.5451      1.126        123        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.62      0.599      0.628      0.414



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      70/80      5.29G      1.064     0.5384      1.122         62        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.614      0.601      0.628      0.414


Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      71/80      5.61G      1.057     0.4817      1.134         59        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.644      0.584      0.627      0.411



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      72/80      5.28G      1.056     0.4769      1.137         56        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.632      0.599      0.628      0.414



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      73/80      5.34G      1.044     0.4691      1.126         51        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.614      0.601      0.628      0.414



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      74/80      5.06G      1.044     0.4654      1.133         67        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.645      0.583      0.628      0.415



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      75/80      5.54G      1.041     0.4633      1.134         68        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.614      0.598      0.628      0.415



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      76/80      4.88G       1.04     0.4627       1.13        121        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.615      0.602      0.628      0.414



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      77/80       5.4G      1.036     0.4634      1.127         68        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.63      0.591      0.628      0.415



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      78/80      5.16G      1.037     0.4655      1.132         42        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.623      0.599      0.627      0.415

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      79/80      5.05G      1.033     0.4608      1.123         51        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867      0.637      0.594      0.628      0.415



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      80/80      5.73G      1.035     0.4593      1.127         71        960: 100%|██████████| 219/
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        750       3867       0.62      0.601      0.628      0.416



80 epochs completed in 0.515 hours.
Optimizer stripped from /home/lablee/Documents/wm/projectdl/runs/yolov8n_960_e80/weights/last.pt, 6.3MB
Optimizer stripped from /home/lablee/Documents/wm/projectdl/runs/yolov8n_960_e80/weights/best.pt, 6.3MB

Validating /home/lablee/Documents/wm/projectdl/runs/yolov8n_960_e80/weights/best.pt...
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
Model summary (fused): 168 layers, 3,006,233 parameters, 0 gradients, 8.1 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████


                   all        750       3867      0.622      0.598      0.628      0.416
Speed: 0.2ms preprocess, 0.7ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to /home/lablee/Documents/wm/projectdl/runs/yolov8n_960_e80
Ultralytics 8.3.40 🚀 Python-3.10.20 torch-2.7.1+cu126 CUDA:0 (NVIDIA GeForce RTX 4090, 24060MiB)
Model summary (fused): 168 layers, 3,006,233 parameters, 0 gradients, 8.1 GFLOPs


val: Scanning /home/lablee/Documents/wm/projectdl/data/yolo/labels/test.cache... 749 images, 0 backg
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|█████

                   all        749       3852      0.614      0.594      0.628      0.413
Speed: 0.3ms preprocess, 1.4ms inference, 0.0ms loss, 0.6ms postprocess per image


[imgsz=960] mAP50=0.6280 mAP50-95=0.4132 FPS=86.5


,imgsz,batch,mAP50,mAP50_95,precision,recall,AP50_helmet,AP50_head,AP50_person,fps,ms_per_img,train_time_min
0,416,32,0.6232,0.4035,0.6038,0.5788,0.9502,0.9059,0.0134,105.0,9.526,16.1
1,640,32,0.6289,0.4132,0.6307,0.6157,0.9558,0.9160,0.0149,256.1,3.905,NaN
2,960,16,0.6280,0.4132,0.6138,0.5936,0.9581,0.9152,0.0106,86.5,11.561,32.8


In [20]:
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

x = res_df["imgsz"].astype(str)
axes[0].plot(x, res_df["mAP50"], "o-", lw=2, label="mAP@0.5")
axes[0].plot(x, res_df["mAP50_95"], "s-", lw=2, label="mAP@0.5:0.95")
axes[0].set_title("(a) Độ chính xác theo độ phân giải")
axes[0].set_xlabel("imgsz"); axes[0].legend(fontsize=8)

ax2 = axes[1]
ax2.bar(x, res_df["fps"], color="#DD8452", alpha=0.85)
ax2.set_ylabel("FPS (batch=1)", color="#DD8452")
ax2.set_title("(b) Tốc độ suy luận"); ax2.set_xlabel("imgsz")
ax2b = ax2.twinx(); ax2b.grid(False)
ax2b.plot(x, res_df["ms_per_img"], "ko--", lw=1.5)
ax2b.set_ylabel("ms / ảnh")

axes[2].plot(res_df["fps"], res_df["mAP50_95"], "o-", lw=2, color="#4C72B0")
for _, r in res_df.iterrows():
    axes[2].annotate(f"{int(r['imgsz'])}", (r["fps"], r["mAP50_95"]),
                     textcoords="offset points", xytext=(6, 6), fontsize=9)
axes[2].set_xlabel("FPS"); axes[2].set_ylabel("mAP@0.5:0.95")
axes[2].set_title("(c) Đường đánh đổi chính xác ↔ tốc độ")

plt.savefig(ARTIFACT_DIR / "fig12_resolution_tradeoff.png", dpi=150, bbox_inches="tight")
plt.show()

<Figure size 1650x440 with 4 Axes>

> **Gợi ý viết phần phân tích cho §7.** Đối chiếu với thống kê kích thước ở notebook 01: nếu phần lớn đối tượng thuộc nhóm `small` (cạnh < 32 px trên ảnh gốc), thì ở `imgsz=416` một cái đầu chỉ còn vài pixel sau khi qua stride 8 — về mặt vật lý là không đủ thông tin. Đây là lời giải thích **cơ chế**, không phải mô tả lại con số. Ngược lại, hãy kiểm tra xem lợi ích khi lên 960 có bão hòa không: nếu mAP tăng ít mà FPS giảm mạnh, kết luận thực hành là 640 nằm ở "khuỷu" của đường đánh đổi.

## 8. Nhật ký thí nghiệm

Đề bài yêu cầu nộp *"file CSV ghi lại mọi lượt chạy (ngày giờ, cấu hình, seed, kết quả)"*, và cảnh báo **"số liệu không khớp giữa báo cáo và log: xử lý như gian lận học thuật"**. Mọi con số trong báo cáo phải truy được về một dòng trong file này.

In [21]:
log = read_log()
print(f"Tổng số lượt chạy đã ghi: {len(log)}")
print("\nSố lượt theo loại thí nghiệm:")
print(log["stage"].value_counts().to_string())
display(log.tail(12))

print(f"\nFile nhật ký: {config.EXPERIMENT_LOG}")

Tổng số lượt chạy đã ghi: 39

Số lượt theo loại thí nghiệm:
stage
sweep_2d      20
sweep_iou      7
sweep_conf     7
resolution     3
val            2


,timestamp,run_id,stage,model,dataset,split,imgsz,epochs,batch,seed,...,mAP50,mAP50_95,precision,recall,f1,fps,ms_per_img,train_time_min,gpu,notes
27,2026-08-22 22:32:21,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.614465,0.429787,0.616425,0.575772,0.595406,71.67,13.952,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
28,2026-08-22 22:32:28,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.614352,0.434150,0.622492,0.582073,0.601604,702.86,1.423,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
29,2026-08-22 22:32:32,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.614361,0.434160,0.622129,0.582190,0.601497,640.37,1.562,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
30,2026-08-22 22:32:39,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.614470,0.434074,0.621366,0.582722,0.601424,706.47,1.415,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
31,2026-08-22 22:32:44,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.613264,0.432988,0.616028,0.580359,0.597662,898.82,1.113,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
32,2026-08-22 22:32:49,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.603537,0.430387,0.634120,0.559292,0.594360,951.14,1.051,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
33,2026-08-22 22:32:53,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.603731,0.430395,0.633750,0.559779,0.594472,793.95,1.260,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
34,2026-08-22 22:32:59,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.603774,0.430301,0.632485,0.560265,0.594189,631.56,1.583,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
35,2026-08-22 22:33:06,yolov8n_640_e80,sweep_2d,yolov8n,NaN,val,640,NaN,NaN,42,...,0.603297,0.429896,0.627595,0.560498,0.592152,553.46,1.807,NaN,NVIDIA GeForce RTX 4090,lưới 2D conf x iou
36,2026-08-22 22:49:45,yolov8n_416_e80,resolution,yolov8n,hardhat-5k,test,416,80.0,32.0,42,...,0.623153,0.403505,0.603765,0.578845,0.591043,105.00,9.526,16.1,NVIDIA GeForce RTX 4090,khảo sát độ phân giải; AP50_helmet=0.9502; AP5...



File nhật ký: /home/lablee/Documents/wm/projectdl/logs/experiment_log.csv


In [22]:
# Lưu gọn cấu hình tốt nhất để notebook 03/04 dùng lại
best_cfg = {
    "weights": str(best_ckpt),
    "imgsz": BASE_IMGSZ,
    "conf_deploy": float(BEST_CONF),
    "iou_deploy": float(BEST_IOU),
    "conf_eval": DEFAULT_CONF,
    "iou_eval": DEFAULT_IOU,
    "test_mAP50": float(overall["mAP50"]),
    "test_mAP50_95": float(overall["mAP50_95"]),
}
json.dump(best_cfg, open(ARTIFACT_DIR / "best_config.json", "w"), indent=2)
print(json.dumps(best_cfg, indent=2, ensure_ascii=False))

{
  "weights": "/home/lablee/Documents/wm/projectdl/runs/yolov8n_640_e80/weights/best.pt",
  "imgsz": 640,
  "conf_deploy": 0.4,
  "iou_deploy": 0.4,
  "conf_eval": 0.001,
  "iou_eval": 0.7,
  "test_mAP50": 0.628917959240961,
  "test_mAP50_95": 0.41318532487749754
}


---

## 9. Kết luận notebook 02

**Đã hoàn thành:**

- [x] Fine-tune YOLOv8n từ trọng số COCO, có đường cong huấn luyện
- [x] Báo cáo mAP@0.5 và mAP@0.5:0.95 trên cả val và test
- [x] Precision–recall curve **theo từng lớp**
- [x] Quét ngưỡng confidence — 7 giá trị (yêu cầu ≥ 5)
- [x] Quét ngưỡng NMS — 7 giá trị (yêu cầu ≥ 5), cộng thêm lưới 2D
- [x] Giải thích anchor box / IoU / NMS kèm minh họa dựng từ chính mô hình
- [x] *(nâng cao)* Khảo sát độ phân giải 416/640/960 với train lại đầy đủ + đo FPS chuẩn
- [x] Nhật ký thí nghiệm ghi đầy đủ

**Còn thiếu để hoàn tất Yêu cầu bắt buộc:**

> *"Phân tích lỗi định lượng: phân loại lỗi thành nhầm lớp / định vị lệch / bỏ sót / phát hiện thừa, thống kê theo kích thước vật thể, kèm ≥ 8 ảnh minh họa."*

Đây là phần chiếm trọng số cao nhất trong thang điểm *Thí nghiệm và phân tích* (25đ) và sẽ là nội dung của **`04_error_analysis.ipynb`**. Ý tưởng: ghép từng dự đoán với hộp thật bằng **thuật toán tham lam (greedy)** — duyệt các dự đoán theo confidence giảm dần, mỗi dự đoán chiếm hộp thật có IoU cao nhất trong số **các hộp chưa bị chiếm**. Rồi phân loại từng lỗi theo cây quyết định (đúng lớp hay không → IoU rơi vào khoảng nào → có ghép được không), sau đó cắt lát thống kê theo `size_bucket` đã tính ở notebook 01.

> **Vì sao greedy chứ không phải Hungarian?** Ghép tối ưu toàn cục (Hungarian) tối đa hoá *tổng* IoU trên cả ảnh, nên có thể hy sinh một cặp ghép tốt để cải thiện tổng — kết quả đẹp về mặt tổ hợp nhưng **không khớp với định nghĩa TP đã viết ở §3** ("IoU với một hộp thật *chưa bị ghép* ≥ ngưỡng"). Chuẩn đánh giá COCO — cũng chính là chuẩn ultralytics dùng để tính mAP mà ta báo cáo — ghép greedy theo confidence. Dùng Hungarian sẽ cho ra bảng lỗi *không cộng lại đúng* với con số mAP ở §3. Greedy vừa đúng định nghĩa, vừa nằm trong phạm vi kiến thức môn học.

**Và `03_faster_rcnn.ipynb`** cho phần nâng cao còn lại: so sánh one-stage (YOLO) với two-stage (Faster R-CNN từ torchvision) về mAP và FPS trên **cùng phần cứng, cùng phép chia dữ liệu**.